---
services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Entity listeners
    entity_listener.event:
        class: App\JSON\ModelParserListener
        autowire: true
        tags:
            - { name: doctrine.orm.entity_listener }

    # Doctrine repository
    App\Repository\Doctrine\BookRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Book ]

    App\Repository\Doctrine\SceneRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Scene ]

    App\Repository\Doctrine\CharacterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Character ]

    App\Repository\Doctrine\ItemRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Item ]

    App\Repository\Doctrine\LocationRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Location ]

    App\Repository\Doctrine\ChapterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Chapter ]

    App\Repository\Doctrine\EventRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\Event ]

    App\Repository\Doctrine\UserRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\User ]

    App\Repository\Doctrine\PasswordResetTokenRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Entity\User\PasswordResetToken ]

    # Repository
    App\Repository\BookRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\SceneRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\CharacterRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\ItemRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\LocationRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\ChapterRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\EventRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    App\Repository\UserRepository:
        autowire: true

    App\Repository\PasswordResetTokenRepository:
        autowire: true
