---
services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Entity listeners
    entity_listener.event:
        class: Talesweaver\Integration\Doctrine\Listener\ModelParserListener
        autoconfigure: false
        tags: [{ name: doctrine.orm.entity_listener }]

    # Entity repository
    Talesweaver\DoctrineRepository\BookRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Book ]

    Talesweaver\DoctrineRepository\CharacterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Character ]

    Talesweaver\DoctrineRepository\ChapterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Chapter ]

    Talesweaver\DoctrineRepository\EventRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Event ]

    Talesweaver\DoctrineRepository\ItemRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Item ]

    Talesweaver\DoctrineRepository\LocationRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Location ]

    Talesweaver\DoctrineRepository\SceneRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Scene ]

    Talesweaver\Integration\Doctrine\Repository\:
        resource: "../../src/Integration/Doctrine/Repository/*"

    # Repository
    _instanceof:
        Talesweaver\Integration\Symfony\Repository\Interfaces\RequestSecuredRepository:
            tags: ['app.param_converter.repository']

    Talesweaver\Integration\Symfony\Repository\:
        resource: "../../src/Integration/Symfony/Repository/*"
