---
services:
    _defaults:
        autoconfigure: true
        autowire: true

    # Entity listeners
    entity_listener.event:
        class: Talesweaver\Integration\Doctrine\Listener\ModelParserListener
        autoconfigure: false
        tags: [{ name: doctrine.orm.entity_listener }]

    # Entity repository
    Talesweaver\Integration\Doctrine\Repository\AuthorRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Author ]

    Talesweaver\Integration\Doctrine\Repository\BookRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Book ]

    Talesweaver\Integration\Doctrine\Repository\CharacterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Character ]

    Talesweaver\Integration\Doctrine\Repository\ChapterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Chapter ]

    Talesweaver\Integration\Doctrine\Repository\EventRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Event ]

    Talesweaver\Integration\Doctrine\Repository\ItemRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Item ]

    Talesweaver\Integration\Doctrine\Repository\LocationRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Location ]

    Talesweaver\Integration\Doctrine\Repository\SceneRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\Scene ]

    Talesweaver\Integration\Doctrine\Repository\PasswordResetTokenRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Talesweaver\Domain\PasswordResetToken ]

    # Repository
    _instanceof:
        Talesweaver\Integration\Symfony\Repository\Interfaces\RequestSecuredRepository:
            tags: ['app.param_converter.repository']

    Talesweaver\Integration\Symfony\Repository\:
        resource: "../../src/Integration/Symfony/Repository/*"
