---
services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Entity listeners
    entity_listener.event:
        class: Integration\JSON\ModelParserListener
        autowire: true
        tags:
            - { name: doctrine.orm.entity_listener }

    # Doctrine repository
    Doctrine\Repository\BookRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Book ]

    Doctrine\Repository\SceneRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Scene ]

    Doctrine\Repository\CharacterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Character ]

    Doctrine\Repository\ItemRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Item ]

    Doctrine\Repository\LocationRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Location ]

    Doctrine\Repository\ChapterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Chapter ]

    Doctrine\Repository\EventRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\Event ]

    Doctrine\Repository\UserRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\User ]

    Doctrine\Repository\PasswordResetTokenRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ Domain\User\PasswordResetToken ]

    # Repository
    Integration\Repository\BookRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\SceneRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\CharacterRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\ItemRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\LocationRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\ChapterRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\EventRepository:
        autowire: true
        tags: ['app.param_converter.repository']

    Integration\Repository\UserRepository:
        autowire: true

    Integration\Repository\PasswordResetTokenRepository:
        autowire: true
