---
framework:
    cache:
        prefix_seed: talesweaver
    csrf_protection:
        enabled: true
    default_locale: '%locale%'
    http_method_override: true
    ide: ~
    php_errors:
        log: true
    session:
        cookie_lifetime: 0
        gc_probability: 0
        handler_id: session.handler.native_file
        save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
    secret: '%env(APP_SECRET)%'
    trusted_hosts: ~
