---
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: { enabled: true }
    http_method_override: true
    trusted_hosts: ~
    session:
        handler_id: ~
        save_path: "%kernel.project_dir%/var/sessions/%kernel.environment%"
        gc_probability: 0
    php_errors:
        log: true
    cache:
        prefix_seed: talesweaver
    ide: ~
    templating:
        engines: [twig]
