framework:
    messenger:
        default_bus: messenger.bus.commands
        buses:
            messenger.bus.commands:
                middleware:
                    - Talesweaver\Integration\Symfony\Bus\Middleware\MessagesMiddleware
                    - Talesweaver\Integration\Symfony\Bus\Middleware\TransactionMiddleware
                    - Talesweaver\Integration\Symfony\Bus\Middleware\AuthorAwareMiddleware
                    - Talesweaver\Integration\Symfony\Bus\Middleware\AuthorAccessMiddleware
            messenger.bus.events:
                middleware:
                    - 'allow_no_handler'
            messenger.bus.queries: ~
