security:
    encoders:
        Domain\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: Domain\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            logout_on_user_change: true
            guard:
                authenticators: [app.security.login_form_authenticator]
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/(pl|en)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/activate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/reset-password/request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/reset-password/change/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
