security:
    encoders:
        Talesweaver\Integration\Doctrine\Entity\User: bcrypt

    providers:
        database_users:
            id: Talesweaver\Integration\Symfony\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: database_users
            guard:
                authenticators: [app.security.login_form_authenticator]
            form_login:
                check_path: login_check
                login_path: login
            logout:
                path:   logout
                target: login

    access_control:
        - { path: ^/(pl|en)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/activate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/reset-password/request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(pl|en)/reset-password/change, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
