services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Integration\Twig\:
        resource: "../../src/Integration/Twig/*"
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
