services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true
        bind:
            $projectDirectory: "%kernel.project_dir%"

    Talesweaver\Integration\Twig\:
        resource: "../../src/Integration/Twig/*"

    Twig\Extensions\TextExtension: ~
