services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    App\Twig\:
        resource: "../../src/App/Twig/*"
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
