services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Talesweaver\Integration\Twig\:
        resource: "../../src/Integration/Twig/*"

    Twig\Extensions\TextExtension: ~
