language: php
php: 7.3
cache:
    yarn: true
    directories:
        - ~/.cache/Cypress
        - node_modules
        - vendor

services: mysql
env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
          DATABASE_URL=mysql://root@127.0.0.1:3306/talesweaver
          WKHTMLTOPDF_PATH=/usr/bin/wkhtmltopdf
          MAILER_URL=null://localhost
          MAILER_FROM=email@example.com
          APP_LOCALE=pl
          APP_ENV=test
          APP_SECRET=some_secret

before_install:
    - mysql -e "SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));";
    - phpenv config-rm xdebug.ini
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - "curl -o- -L https://yarnpkg.com/install.sh | bash -s --"
    - "export PATH=$HOME/.yarn/bin:$PATH"

install:
    - composer install -n
    - composer validate
    - composer run create-schema
    - nvm install 10

script:
    - composer run sniffer
    - composer run deptrac
    - composer run linters
    - composer run stan
    - composer run validate-schema
    - node_modules/.bin/webpack
    - composer run codecept
    - bin/console doctrine:fixtures:load -n --group=integration
    - APP_ENV=test php -d variables_order=EGPCS -S 127.0.0.1:8000 -t public > var/log/server.log 2>&1 &
    - yarn install
    - node_modules/.bin/cypress run

after_failure:
    - cat var/log/test.log
    - cat var/log/test_cypress.log
    - cat var/log/server.log
