language: php

cache:
    yarn: true
    directories:
        - bin
        - vendor
        - node_modules

sudo: false

addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server

matrix:
    include:
        - php: 7.1
          env: SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
    - composer install -n
    - yarn install
    - bin/console server:start

script:
    - bin/phpcs
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:create --env=test
    # Temporary turned off, since it does not detect JSON column
    #- bin/console doctrine:schema:validate --env=test
    - bin/codecept run
    - node_modules/cypress/bin/cypress run
