language: php

cache:
    yarn: true
    directories:
        - bin
        - node_modules
        - vendor

sudo: false

addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server

matrix:
    include:
        - php: 7.2
          env: SYMFONY_DEPRECATIONS_HELPER=weak

before_install:
    - phpenv config-rm xdebug.ini
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
    - export PATH=$HOME/.yarn/bin:$PATH

install:
    - composer install -n
    - rm .env
    - cp .env.travis .env
    - bin/console doctrine:database:create
    - bin/console doctrine:schema:create
    - bin/console doctrine:schema:validate

script:
    - bin/phpcs
    - bin/codecept run
    - bin/console doctrine:fixtures:load -n
    - bin/console server:start
    - yarn install
    - node_modules/.bin/webpack
    - node_modules/.bin/cypress run
