language: php

cache:
    yarn: true
    directories:
        - bin
        - node_modules
        - vendor

sudo: false

addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server

matrix:
    include:
        - php: 7.1
          env: SYMFONY_DEPRECATIONS_HELPER=weak

install:
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install -n
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:schema:create --env=test
    - bin/console server:start
    - yarn install
    - node_modules/.bin/webpack

script:
#    - bin/phpcs
#    - bin/console doctrine:schema:validate --env=test
#    - bin/codecept run
    - bin/console doctrine:fixtures:load -n --env=test
    - node_modules/.bin/cypress run
