language: php

cache:
  directories:
    - bin
    - vendor

sudo: false

addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server

matrix:
    include:
        - php: 7.1
          env: SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - composer install -n

script:
  - bin/phpcs
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  # Temporary turned off, since it does not detect JSON column
  #- bin/console doctrine:schema:validate --env=test
  - bin/codecept run
