language: php

cache:
  directories:
    - bin
    - vendor

sudo: false

matrix:
    include:
        - php: 7.1
          env: SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
  - composer install -n -v

script:
  - bin/phpcs
  - bin/security-checker security:check
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  - bin/console doctrine:schema:validate --env=test -n
  - bin/codecept run
