language: php

cache:
    yarn: true
    directories:
        - bin
        - node_modules
        - vendor

sudo: false

addons:
    apt:
        sources:
            - mysql-5.7-trusty
        packages:
            - mysql-server

matrix:
    include:
        - php: 7.1
          env: SYMFONY_DEPRECATIONS_HELPER=weak SYMFONY_ENV=test

before_install:
    - echo 'date.timezone = "Europe/Warsaw"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2

install:
    - composer install -n
    - bin/console ckeditor:install -n --clear=skip
    - bin/console assets:install --symlink
    - bin/console doctrine:database:create
    - bin/console doctrine:schema:create
    - bin/console server:start
    - yarn install
    - node_modules/.bin/webpack

script:
    - bin/phpcs
    - bin/console doctrine:schema:validate
    - bin/codecept run
    - bin/console doctrine:fixtures:load -n
    - 'node_modules/.bin/cypress run --config baseUrl=http://127.0.0.1:8000/pl'
