language: php

cache:
  directories:
    - bin
    - vendor

sudo: false

php:
  - 7.1

before_script:
  - composer install -n --prefer-dist -v

script:
  - bin/phpcs
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  - bin/console doctrine:schema:validate --env=test -n
