---
admin_login:
    path: /login
    controller: Talesweaver\Application\Controller\Administration\LoginController
    methods: [GET,POST]

admin_index:
    path: /
    controller: Talesweaver\Application\Controller\Administration\IndexController
    methods: GET

admin_author_list:
    path: /author/list
    controller: Talesweaver\Application\Controller\Administration\Author\ListController
    methods: GET

admin_logout:
    path: /logout
