---
index:
    path: /
    controller: Talesweaver\Application\Controller\DashboardController
    methods:  GET

about:
    path: /page/about
    controller: Talesweaver\Application\Controller\Information\AboutController
    methods:  GET

alerts:
    path: /alerts
    controller: Talesweaver\Application\Controller\AlertsController
    methods:  GET
    condition: "request.isXmlHttpRequest()"

sort:
    path: /sort/{list}/{direction}/{field}/{redirect}
    controller: Talesweaver\Application\Controller\SortController
    methods:  GET
    requirements:
        direction: asc|desc
        redirect: .+
