---
index:
    path: /
    controller: Integration\Controller\DashboardController
    methods:  GET

alerts:
    path: /alerts
    controller: Integration\Controller\AlertsController
    methods:  GET
    condition: "request.isXmlHttpRequest()"
