---
index:
    path: /
    controller: Talesweaver\Application\Controller\DashboardController
    methods: GET

about:
    path: /page/about
    controller: Talesweaver\Application\Controller\AboutController
    methods: GET

first_steps:
    path: /page/first-steps
    controller: Talesweaver\Application\Controller\FirstStepsController
    methods: GET

alerts:
    path: /alerts
    controller: Talesweaver\Application\Controller\AlertsController
    methods: GET
    condition: "request.isXmlHttpRequest()"
