---
book_create:
    path: /create/{page}
    controller: Talesweaver\Application\Controller\Book\CreateController
    defaults:
        page: 1
    methods:  [GET, POST]

book_edit:
    path: /edit/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\EditController
    defaults:
        page: 1
    methods:  [GET, POST]

book_list:
    path: /list/{page}
    controller: Talesweaver\Application\Controller\Book\ListController
    defaults:
        page: 1
    methods:  GET

book_delete:
    path: /delete/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\DeleteController
    defaults:
        page: 1
    methods:  GET

book_chapter_list:
    path: /chapters/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\ChaptersListController
    defaults:
        page: 1
    condition: "request.isXmlHttpRequest()"
    methods:  GET
