---
book_create:
    path: /create/{page}
    controller: Talesweaver\Application\Controller\Book\CreateController
    defaults:
        page: 1
    methods:  [GET, POST]

book_edit:
    path: /edit/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\EditController
    defaults:
        page: 1
    methods:  [GET, POST]

book_list:
    path: /list/{page}
    controller: Talesweaver\Application\Controller\Book\ListController
    defaults:
        page: 1
    methods:  GET

book_delete:
    path: /delete/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\DeleteController
    defaults:
        page: 1
    methods:  GET

book_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Book\DisplayController
    methods:  GET

book_publish:
    path: /publish/{id}
    controller: Talesweaver\Application\Controller\Book\PublishController
    methods:  GET|POST

book_publication_list:
    path: /publications/{id}
    controller: Talesweaver\Application\Controller\Book\PublicationListController
    methods:  GET

book_pdf:
    path: /pdf/{id}
    controller: Talesweaver\Application\Controller\Book\PdfController
    methods:  GET

book_chapter_list:
    path: /chapters/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\ChaptersListController
    defaults:
        page: 1
    condition: "request.isXmlHttpRequest()"
    methods:  GET

book_add_chapter:
    path: /chapter/{id}
    controller: Talesweaver\Application\Controller\Book\ChapterAddController
    methods: [GET, POST]
    condition: "request.isXmlHttpRequest()"

book_scene_list:
    path: /scenes/{id}/{page}
    controller: Talesweaver\Application\Controller\Book\ScenesListController
    defaults:
        page: 1
    condition: "request.isXmlHttpRequest()"
    methods:  GET
