---
chapter_create:
    path: /create/{page}/{bookId}
    controller: Talesweaver\Application\Controller\Chapter\CreateController
    defaults:
        page: 1
        bookId: null
    methods: [GET, POST]

chapter_edit:
    path: /edit/{id}/{page}
    controller: Talesweaver\Application\Controller\Chapter\EditController
    defaults:
        page: 1
    methods: [GET, POST]

chapter_list:
    path: /list/{page}
    controller: Talesweaver\Application\Controller\Chapter\ListController
    defaults:
        page: 1
    methods: GET

chapter_scenes_list:
    path: /scenes/{id}/{page}
    controller: Talesweaver\Application\Controller\Chapter\ScenesListController
    defaults:
        page: 1
    condition: "request.isXmlHttpRequest()"
    methods: GET

chapter_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Chapter\DisplayController
    methods: GET

chapter_add_scene:
    path: /scene/{id}
    controller: Talesweaver\Application\Controller\Chapter\SceneAddController
    methods: [GET, POST]
    condition: "request.isXmlHttpRequest()"

chapter_delete:
    path: /delete/{id}/{page}
    controller: Talesweaver\Application\Controller\Chapter\DeleteController
    defaults:
        page: 1
    methods: GET

chapter_publish:
    path: /publish/{id}
    controller: Talesweaver\Application\Controller\Chapter\PublishController
    methods: [GET,POST]

chapter_publication_list:
    path: /publications/{id}
    controller: Talesweaver\Application\Controller\Chapter\PublicationListController
    methods: GET

chapter_pdf:
    path: /pdf/{id}
    controller: Talesweaver\Application\Controller\Chapter\PdfController
    methods: GET

chapter_position_multiple:
    path: /position/multiple
    controller: Talesweaver\Application\Controller\Chapter\PositionController
    methods: POST
    condition: "request.isXmlHttpRequest()"
