---
chapter_create:
    path: /create/{page}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\CreateController, page: 1 }
    methods:  [GET, POST]

chapter_edit:
    path: /edit/{id}/{page}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\EditController, page: 1 }
    methods:  [GET, POST]

chapter_list:
    path: /list/{page}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\ListController, page: 1 }
    methods:  GET

chapter_scenes_list:
    path: /scenes/{id}/{page}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\ScenesListController, page: 1 }
    condition: "request.isXmlHttpRequest()"
    methods:  GET

chapter_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\DeleteController, page: 1 }
    methods:  GET

chapter_display:
    path: /display/{id}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\DisplayController }
    methods:  GET

chapter_pdf:
    path: /pdf/{id}
    defaults: { _controller: Talesweaver\Integration\Symfony\Controller\Chapter\PdfController }
    methods:  GET
