---
character_new:
    path: /new/{id}
    controller: Talesweaver\Application\Controller\Character\CreateController
    methods:  [GET, POST]

character_edit:
    path: /edit/{id}
    controller: Talesweaver\Application\Controller\Character\EditController
    methods:  [GET, POST]

character_list:
    path: /list/{id}/{page}
    controller: Talesweaver\Application\Controller\Character\ListController
    defaults:
        page: 1
    methods:  GET

character_delete:
    path: /delete/{id}
    controller: Talesweaver\Application\Controller\Character\DeleteController
    methods:  GET

character_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Character\DisplayController
    methods:  GET

character_related:
    path: /related/{id}/{page}
    controller: Talesweaver\Application\Controller\Character\ListRelatedController
    defaults:
        page: 1
    methods:  GET

character_add_to_scene:
    path: /add-to-scene/{scene_id}/{id}
    controller: Talesweaver\Application\Controller\Character\AddToSceneController
    methods:  GET

character_remove_from_scene:
    path: /remove-from-scene/{scene_id}/{id}
    controller: Talesweaver\Application\Controller\Character\RemoveFromSceneController
    methods:  GET
