---
event_list:
    path: /list/{id}/{page}
    defaults: { _controller: Integration\Controller\Event\ListController, page: 1 }
    methods:  GET

event_options:
    path: /options/{id}
    defaults: { _controller: Integration\Controller\Event\OptionsListController }
    methods:  GET

event_add:
    path: /add/{id}/{model}
    defaults: { _controller: Integration\Controller\Event\CreateController }
    methods:  GET|POST
    requirements:
        model: .+

event_edit:
    path: /edit/{id}
    defaults: { _controller: Integration\Controller\Event\EditController }
    methods:  GET|POST

event_display:
    path: /dsiplay/{id}
    defaults: { _controller: Integration\Controller\Event\DisplayController }
    methods:  GET

event_delete:
    path: /delete/{id}
    defaults: { _controller: Integration\Controller\Event\DeleteController }
    methods:  GET
