---
event_list:
    path: /list/{id}/{page}
    controller: Talesweaver\Application\Controller\Event\ListController
    defaults:
        page: 1
    methods:  GET

event_options:
    path: /options/{id}
    controller: Talesweaver\Application\Controller\Event\OptionsListController
    methods:  GET

event_add:
    path: /add/{id}/{model}
    controller: Talesweaver\Application\Controller\Event\CreateController
    methods:  GET|POST
    requirements:
        model: .+

event_edit:
    path: /edit/{id}
    controller: Talesweaver\Application\Controller\Event\EditController
    methods:  GET|POST

event_display:
    path: /dsiplay/{id}
    controller: Talesweaver\Application\Controller\Event\DisplayController
    methods:  GET

event_delete:
    path: /delete/{id}
    controller: Talesweaver\Application\Controller\Event\DeleteController
    methods:  GET
