---
item_new:
    path: /new/{id}
    controller: Talesweaver\Application\Controller\Item\CreateController
    methods:  [GET, POST]

item_edit:
    path: /edit/{id}
    controller: Talesweaver\Application\Controller\Item\EditController
    methods:  [GET, POST]

item_list:
    path: /list/{id}/{page}
    controller: Talesweaver\Application\Controller\Item\ListController
    defaults:
        page: 1
    methods:  GET

item_delete:
    path: /delete/{id}
    controller: Talesweaver\Application\Controller\Item\DeleteController
    methods:  GET

item_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Item\DisplayController
    methods:  GET

item_related:
    path: /related/{id}/{page}
    controller: Talesweaver\Application\Controller\Item\ListRelatedController
    defaults:
        page: 1
    methods:  GET

item_add_to_scene:
    path: /add-to-scene/{scene_id}/{item_id}
    controller: Talesweaver\Application\Controller\Item\AddToSceneController
    methods:  GET

item_remove_from_scene:
    path: /remove-from-scene/{scene_id}/{item_id}
    controller: Talesweaver\Application\Controller\Item\RemoveFromSceneController
    methods:  GET
