---
location_new:
    path: /new/{id}
    controller: Talesweaver\Application\Controller\Location\CreateController
    methods:  [GET, POST]

location_edit:
    path: /edit/{id}
    controller: Talesweaver\Application\Controller\Location\EditController
    methods:  [GET, POST]

location_list:
    path: /list/{id}/{page}
    controller: Talesweaver\Application\Controller\Location\ListController
    defaults:
        page: 1
    methods:  GET

location_delete:
    path: /delete/{id}
    controller: Talesweaver\Application\Controller\Location\DeleteController
    methods:  GET

location_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Location\DisplayController
    methods:  GET

location_related:
    path: /related/{id}/{page}
    controller: Talesweaver\Application\Controller\Location\ListRelatedController
    defaults:
        page: 1
    methods:  GET

location_add_to_scene:
    path: /add-to-scene/{scene_id}/{id}
    controller: Talesweaver\Application\Controller\Location\AddToSceneController
    methods:  GET

location_remove_from_scene:
    path: /remove-from-scene/{scene_id}/{id}
    controller: Talesweaver\Application\Controller\Location\RemoveFromSceneController
    methods:  GET
