---
publication_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Publication\DisplayController
    methods: GET

publication_public_display:
    path: /display-public/{id}
    controller: Talesweaver\Application\Controller\Publication\PublicDisplayController
    methods: GET

publication_toggle_visibility:
    path: /toggle/{id}
    controller: Talesweaver\Application\Controller\Publication\TogglePublicVisibilityController
    condition: "request.isXmlHttpRequest()"
    methods: GET

publication_delete:
    path: /delete/{id}
    controller: Talesweaver\Application\Controller\Publication\DeleteController
    condition: "request.isXmlHttpRequest()"
    methods: GET
