---
publication_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Publication\DisplayController
    methods: GET

publication_delete:
    path: /delete/{id}
    controller: Talesweaver\Application\Controller\Publication\DeleteController
    condition: "request.isXmlHttpRequest()"
    methods: GET
