---
scene_create:
    path: /create/{page}
    controller: Talesweaver\Application\Controller\Scene\CreateController
    defaults:
        page: 1
    methods:  [GET, POST]

scene_edit:
    path: /edit/{id}
    controller: Talesweaver\Application\Controller\Scene\EditController
    methods:  [GET, POST]

scene_list:
    path: /list/{page}
    controller: Talesweaver\Application\Controller\Scene\ListController
    defaults:
        page: 1
    methods:  GET

scene_related_list:
    path: /related-list/{id}/{page}
    controller: Talesweaver\Application\Controller\Scene\RelatedListController
    defaults:
        page: 1
    methods:  GET

scene_delete:
    path: /delete/{id}/{page}
    controller: Talesweaver\Application\Controller\Scene\DeleteController
    defaults:
        page: 1
    methods:  GET

scene_display:
    path: /display/{id}
    controller: Talesweaver\Application\Controller\Scene\DisplayController
    methods:  GET

scene_position_single_increase:
    path: /position/single/increase/{id}
    controller: Talesweaver\Application\Controller\Scene\IncreasePositionController
    methods: GET
    condition: "request.isXmlHttpRequest()"

scene_position_single_decrease:
    path: /position/single/decrease/{id}
    controller: Talesweaver\Application\Controller\Scene\DecreasePositionController
    methods: GET
    condition: "request.isXmlHttpRequest()"

scene_position_multiple:
    path: /position/multiple
    controller: Talesweaver\Application\Controller\Scene\PositionController
    methods: POST
    condition: "request.isXmlHttpRequest()"

scene_publish:
    path: /publish/{id}
    controller: Talesweaver\Application\Controller\Scene\PublishController
    methods:  GET|POST

scene_publication_list:
    path: /publications/{id}
    controller: Talesweaver\Application\Controller\Scene\PublicationListController
    methods:  GET

scene_pdf:
    path: /pdf/{id}
    controller: Talesweaver\Application\Controller\Scene\PdfController
    methods:  GET
