---
login:
    path: /login
    defaults: { _controller: Integration\Controller\Security\LoginController }
    methods:  GET|POST

register:
    path: /registration
    defaults: { _controller: Integration\Controller\Security\RegisterController }
    methods:  GET|POST

activation:
    path: /activate/{code}
    defaults: { _controller: Integration\Controller\Security\ActivationController }
    methods:  GET

password_reset_request:
    path: /reset-password/request
    defaults: { _controller: Integration\Controller\Security\ResetPasswordRequestController }
    methods:  GET|POST

password_reset_change:
    path: /reset-password/change/{code}
    defaults: { _controller: Integration\Controller\Security\ResetPasswordChangeController }
    methods:  GET|POST

change_password:
    path: /change-password
    defaults: { _controller: Integration\Controller\Security\ChangePasswordController }
    methods:  GET|POST
