---
services:
    app.controller.dashboard:
        class: AppBundle\Controller\DashboardController
        arguments:
            - "@templating"
            - "@app.repository.book"
            - "@app.repository.chapter"
            - "@app.repository.scene"

    # Book
    app.controller.book.create:
        class: AppBundle\Controller\Book\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.book.edit:
        class: AppBundle\Controller\Book\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.book"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.book.list:
        class: AppBundle\Controller\Book\ListController
        arguments:
            - "@templating"
            - "@app.paginator.aggregate.book"

    app.controller.book.delete:
        class: AppBundle\Controller\Book\DeleteController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Chapter
    app.controller.chapter:
        class: AppBundle\Controller\ChapterController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.chapter"
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Scene
    app.controller.scene:
        class: AppBundle\Controller\SceneController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.scene"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.character:
        class: AppBundle\Controller\CharacterController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.character"
            - "@router"

    app.controller.item:
        class: AppBundle\Controller\ItemController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.item"
            - "@router"

    app.controller.location:
        class: AppBundle\Controller\LocationController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.location"
            - "@router"

    app.controller.event:
        class: AppBundle\Controller\EventController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@app.paginator.event"

    # Display
    app.controller.display:
        class: AppBundle\Controller\DisplayController
        arguments:
            - "@templating"

    # PDF
    app.controller.pdf:
        class: AppBundle\Controller\PDFController
        arguments:
            - "@templating"
            - "@knp_snappy.pdf"
