---
services:
    app.controller.dashboard:
        class: AppBundle\Controller\DashboardController
        arguments:
            - "@templating"
            - "@app.repository.book"
            - "@app.repository.chapter"
            - "@app.repository.scene"

    # Book
    app.controller.book.create:
        class: AppBundle\Controller\Book\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.book.edit:
        class: AppBundle\Controller\Book\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.book"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.book.list:
        class: AppBundle\Controller\Book\ListController
        arguments:
            - "@templating"
            - "@app.paginator.aggregate.book"

    app.controller.book.delete:
        class: AppBundle\Controller\Book\DeleteController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Chapter
    app.controller.chapter.create:
        class: AppBundle\Controller\Chapter\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.chapter.edit:
        class: AppBundle\Controller\Chapter\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.chapter"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.chapter.list:
        class: AppBundle\Controller\Chapter\ListController
        arguments:
            - "@templating"
            - "@app.paginator.aggregate.chapter"

    app.controller.chapter.delete:
        class: AppBundle\Controller\Chapter\DeleteController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Scene
    app.controller.scene.create:
        class: AppBundle\Controller\Scene\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.scene.edit:
        class: AppBundle\Controller\Scene\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.scene"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.scene.list:
        class: AppBundle\Controller\Scene\ListController
        arguments:
            - "@templating"
            - "@app.paginator.aggregate.scene"

    app.controller.scene.delete:
        class: AppBundle\Controller\Scene\DeleteController
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Character
    app.controller.character.create:
        class: AppBundle\Controller\Character\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.character.edit:
        class: AppBundle\Controller\Character\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.character"
            - "@router"

    app.controller.character.list:
        class: AppBundle\Controller\Character\ListController
        arguments:
            - "@templating"
            - "@app.paginator.character"

    app.controller.character.delete:
        class: AppBundle\Controller\Character\DeleteController
        arguments:
            - "@templating"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.character"

    app.controller.character.display:
        class: AppBundle\Controller\Character\DisplayController
        arguments:
            - "@templating"

    # Item
    app.controller.item.create:
        class: AppBundle\Controller\Item\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.item.edit:
        class: AppBundle\Controller\Item\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.item"
            - "@router"

    app.controller.item.list:
        class: AppBundle\Controller\Item\ListController
        arguments:
            - "@templating"
            - "@app.paginator.item"

    app.controller.item.delete:
        class: AppBundle\Controller\Item\DeleteController
        arguments:
            - "@templating"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.item"

    app.controller.item.display:
        class: AppBundle\Controller\Item\DisplayController
        arguments:
            - "@templating"

    app.controller.location:
        class: AppBundle\Controller\LocationController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.location"
            - "@router"

    app.controller.event:
        class: AppBundle\Controller\EventController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@app.paginator.event"

    # Display
    app.controller.display:
        class: AppBundle\Controller\DisplayController
        arguments:
            - "@templating"

    # PDF
    app.controller.pdf:
        class: AppBundle\Controller\PDFController
        arguments:
            - "@templating"
            - "@knp_snappy.pdf"
