---
services:
    app.controller.base:
        class: AppBundle\Controller\BaseController
        arguments:
            - @templating

    app.controller.scene:
        class: AppBundle\Controller\SceneController
        arguments:
            - @templating
            - @form.factory
            - @doctrine.orm.entity_manager
            - @router
