---
services:
    app.controller.dashboard:
        class: AppBundle\Controller\DashboardController
        arguments:
            - "@templating"
            - "@app.repository.book"
            - "@app.repository.chapter"
            - "@app.repository.scene"

    # Abstract
    app.controller.abstract.form:
        abstract: true
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.abstract.templating:
        abstract: true
        arguments: ["@templating"]

    app.controller.abstract.delete:
        abstract: true
        arguments: ["@doctrine.orm.entity_manager"]

    # Book
    app.controller.book.create:
        class: AppBundle\Controller\Book\CreateController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@event_bus"
            - "@router"

    app.controller.book.edit:
        class: AppBundle\Controller\Book\EditController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@event_bus"
            - "@router"

    app.controller.book.list:
        class: AppBundle\Controller\Book\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.aggregate.book"

    app.controller.book.delete:
        class: AppBundle\Controller\Book\DeleteController
        parent: app.controller.abstract.delete
        arguments: ["@router"]

    # Chapter
    app.controller.chapter.create:
        class: AppBundle\Controller\Chapter\CreateController
        parent: app.controller.abstract.form

    app.controller.chapter.create_assigned:
        class: AppBundle\Controller\Chapter\CreateAssignedController
        parent: app.controller.abstract.form

    app.controller.chapter.edit:
        class: AppBundle\Controller\Chapter\EditController
        parent: app.controller.abstract.form
        arguments:
            - "@app.paginator.aggregate.chapter"

    app.controller.chapter.list:
        class: AppBundle\Controller\Chapter\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.aggregate.chapter"

    app.controller.chapter.delete:
        class: AppBundle\Controller\Chapter\DeleteController
        parent: app.controller.abstract.delete
        arguments: ["@router"]

    app.controller.chapter.display:
        class: AppBundle\Controller\Chapter\DisplayController
        parent: app.controller.abstract.templating

    # Scene
    app.controller.scene.create:
        class: AppBundle\Controller\Scene\CreateController
        parent: app.controller.abstract.form

    app.controller.scene.create_assigned:
        class: AppBundle\Controller\Scene\CreateAssignedController
        parent: app.controller.abstract.form

    app.controller.scene.edit:
        class: AppBundle\Controller\Scene\EditController
        parent: app.controller.abstract.form
        arguments:
            - "@app.paginator.aggregate.scene"

    app.controller.scene.list:
        class: AppBundle\Controller\Scene\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.aggregate.scene"

    app.controller.scene.delete:
        class: AppBundle\Controller\Scene\DeleteController
        parent: app.controller.abstract.delete
        arguments: ["@router"]

    app.controller.scene.display:
        class: AppBundle\Controller\Scene\DisplayController
        parent: app.controller.abstract.templating

    # Character
    app.controller.character.create:
        class: AppBundle\Controller\Character\CreateController
        parent: app.controller.abstract.form

    app.controller.character.edit:
        class: AppBundle\Controller\Character\EditController
        parent: app.controller.abstract.form

    app.controller.character.list:
        class: AppBundle\Controller\Character\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.character"

    app.controller.character.delete:
        class: AppBundle\Controller\Character\DeleteController
        parent: app.controller.abstract.delete

    app.controller.character.display:
        class: AppBundle\Controller\Character\DisplayController
        parent: app.controller.abstract.templating

    # Item
    app.controller.item.create:
        class: AppBundle\Controller\Item\CreateController
        parent: app.controller.abstract.form

    app.controller.item.edit:
        class: AppBundle\Controller\Item\EditController
        parent: app.controller.abstract.form

    app.controller.item.list:
        class: AppBundle\Controller\Item\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.item"

    app.controller.item.delete:
        class: AppBundle\Controller\Item\DeleteController
        parent: app.controller.abstract.delete

    app.controller.item.display:
        class: AppBundle\Controller\Item\DisplayController
        parent: app.controller.abstract.templating

    # Location
    app.controller.location.create:
        class: AppBundle\Controller\Location\CreateController
        parent: app.controller.abstract.form

    app.controller.location.edit:
        class: AppBundle\Controller\Location\EditController
        parent: app.controller.abstract.form

    app.controller.location.list:
        class: AppBundle\Controller\Location\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.location"

    app.controller.location.delete:
        class: AppBundle\Controller\Location\DeleteController
        parent: app.controller.abstract.delete

    app.controller.location.display:
        class: AppBundle\Controller\Location\DisplayController
        parent: app.controller.abstract.templating

    # Event
    app.controller.event.create:
        class: AppBundle\Controller\Event\CreateController
        parent: app.controller.abstract.form

    app.controller.event.list:
        class: AppBundle\Controller\Event\ListController
        parent: app.controller.abstract.templating
        arguments:
            - "@app.paginator.event"

    app.controller.event.delete:
        class: AppBundle\Controller\Event\DeleteController
        parent: app.controller.abstract.delete

    # PDF
    app.controller.pdf:
        class: AppBundle\Controller\PDFController
        parent: app.controller.abstract.templating
        arguments:
            - "@templating"
            - "@knp_snappy.pdf"
