---
services:
    _defaults:
        autowire: true
        autoconfigure: true

    SimpleBus\Message\Bus\MessageBus: "@command_bus"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"

    AppBundle\Controller\:
        resource: "../../../Controller/*"
