---
services:
    app.controller.dashboard:
        class: AppBundle\Controller\DashboardController
        arguments:
            - "@templating"
            - "@app.repository.chapter"
            - "@app.repository.scene"

    # Chapter
    app.controller.chapter.standalone:
        class: AppBundle\Controller\Chapter\StandaloneController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.single.chapter.standalone"
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Scene
    app.controller.scene.standalone:
        class: AppBundle\Controller\Scene\StandaloneController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.scene"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.scene.character:
        class: AppBundle\Controller\Scene\CharacterController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.scene.item:
        class: AppBundle\Controller\Scene\ItemController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.scene.location:
        class: AppBundle\Controller\Scene\LocationController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@router"
