---
services:
    app.controller.dashboard:
        class: AppBundle\Controller\DashboardController
        arguments:
            - "@templating"
            - "@app.repository.chapter"
            - "@app.repository.scene"

    # Book
    app.controller.book:
        class: AppBundle\Controller\BookController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.book"
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Chapter
    app.controller.chapter:
        class: AppBundle\Controller\ChapterController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.chapter"
            - "@doctrine.orm.entity_manager"
            - "@router"

    # Scene
    app.controller.scene:
        class: AppBundle\Controller\SceneController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@app.paginator.aggregate.scene"
            - "@doctrine.orm.entity_manager"
            - "@router"

    app.controller.character:
        class: AppBundle\Controller\CharacterController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.aggregate.character"
            - "@router"

    app.controller.item:
        class: AppBundle\Controller\ItemController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.aggregate.item"
            - "@router"

    app.controller.location:
        class: AppBundle\Controller\LocationController
        arguments:
            - "@templating"
            - "@form.factory"
            - "@doctrine.orm.entity_manager"
            - "@app.paginator.aggregate.location"
            - "@router"
