---
services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Entity listeners
    entity_listener.event:
        class: AppBundle\Event\ModelParserListener
        autowire: true
        tags:
            - { name: doctrine.orm.entity_listener }

    # Repository
    AppBundle\Entity\Repository\BookRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Book ]

    AppBundle\Entity\Repository\SceneRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Scene ]

    AppBundle\Entity\Repository\CharacterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Character ]

    AppBundle\Entity\Repository\ItemRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Item ]

    AppBundle\Entity\Repository\LocationRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Location ]

    AppBundle\Entity\Repository\ChapterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Chapter ]

    AppBundle\Entity\Repository\EventRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\Event ]

    AppBundle\Entity\Repository\UserRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle\Entity\User ]
