---
services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Repository
    AppBundle\Entity\Repository\BookRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Book ]

    AppBundle\Entity\Repository\SceneRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Scene ]

    AppBundle\Entity\Repository\CharacterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Character ]

    AppBundle\Entity\Repository\ItemRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Item ]

    AppBundle\Entity\Repository\LocationRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Location ]

    AppBundle\Entity\Repository\ChapterRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Chapter ]

    AppBundle\Entity\Repository\EventRepository:
        factory: ["@doctrine", getRepository]
        arguments: [ AppBundle:Event ]
