---
services:
    app.element.manager:
        class: AppBundle\Element\Manager\Manager
        
    app.element.chapter:
        class: AppBundle\Element\ChapterElement
        tags:
            - { name: app.element }
        
    app.element.section:
        class: AppBundle\Element\SectionElement
        tags:
            - { name: app.element }
