---
services:
    # Manager
    app.element.manager:
        class: AppBundle\Element\Manager\Manager

    # Element
    app.element.book:
        class: AppBundle\Element\BookElement
        tags:
            - { name: app.element }

    app.element.chapter:
        class: AppBundle\Element\ChapterElement
        tags:
            - { name: app.element }

    app.element.scene:
        class: AppBundle\Element\SceneElement
        tags:
            - { name: app.element }
