---
services:
    app.element.manager:
        class: AppBundle\Element\Manager\Manager
        
    app.element.paragraph:
        class: AppBundle\Element\ParagraphElement
        tags:
            - { name: app.element }

