---
services:
    app.event.book.create:
        class: AppBundle\Book\Create\EventHandler
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.event_recorder"
        tags:
            - { name: event_subscriber, subscribes_to: AppBundle\Book\Create\Event }

    app.event_recorder:
        class: AppBundle\Event\Recorder

    app.event.book.edit:
        class: AppBundle\Book\Edit\EventHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: event_subscriber, subscribes_to: AppBundle\Book\Edit\Event }
