---
services:
    _defaults:
        autowire: false
        autoconfigure: false

    # Book handlers
    app.command.book.create:
        class: AppBundle\Book\Create\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Book\Create\Command }

    app.command.book.edit:
        class: AppBundle\Book\Edit\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Book\Edit\Command }

    app.command.book.delete:
        class: AppBundle\Book\Delete\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Book\Delete\Command }

    # Chapter handles
    app.command.chapter.create:
        class: AppBundle\Chapter\Create\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Chapter\Create\Command }

    app.command.chapter.edit:
        class: AppBundle\Chapter\Edit\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Chapter\Edit\Command }

    app.command.chapter.delete:
        class: AppBundle\Chapter\Delete\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Chapter\Delete\Command }

    # Scene handles
    app.command.scene.create:
        class: AppBundle\Scene\Create\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Scene\Create\Command }

    app.command.scene.edit:
        class: AppBundle\Scene\Edit\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Scene\Edit\Command }

    app.command.scene.delete:
        class: AppBundle\Scene\Delete\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Scene\Delete\Command }

    # Event handlers
    app.command.event.create:
        class: AppBundle\Event\Create\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Event\Create\Command }

    app.command.event.delete:
        class: AppBundle\Event\Delete\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Event\Delete\Command }

    # Character handlers
    app.command.character.create:
        class: AppBundle\Character\Create\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Character\Create\Command }

    app.command.character.add_to_scene:
        class: AppBundle\Character\AddToScene\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Character\AddToScene\Command }

    app.command.character.edit:
        class: AppBundle\Character\Edit\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Character\Edit\Command }

    app.command.character.delete:
        class: AppBundle\Character\Delete\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Character\Delete\Command }

    app.command.character.remove_from_scene:
        class: AppBundle\Character\RemoveFromScene\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Character\RemoveFromScene\Command }
