---
services:
    # Book handlers
    app.command.book.create:
        class: AppBundle\Book\Create\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Book\Create\Command }

    app.command.book.edit:
        class: AppBundle\Book\Edit\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Book\Edit\Command }

    app.command.book.delete:
        class: AppBundle\Book\Delete\CommandHandler
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: command_handler, handles: AppBundle\Book\Delete\Command }
