---
services:
    # Menu
    app.menu.builder:
        class: AppBundle\Menu\Builder
        arguments:
            - "@knp_menu.factory"

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }
