---
services:
    _defaults:
        autowire: false
        autoconfigure: false

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    app.menu.builder:
        class: AppBundle\Menu\Builder
        arguments:
            - "@knp_menu.factory"

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main }
