---
services:
    # Book
    app.paginator.book:
        class: AppBundle\Pagination\Book\BookPaginator
        arguments:
            - "@app.repository.book"

    app.paginator.book.chapters:
        class: AppBundle\Pagination\Book\ChapterPaginator
        arguments:
            - "@app.repository.chapter"

    # Chapter
    app.paginator.aggregate.chapter:
        class: AppBundle\Pagination\Chapter\ChapterAggregate
        arguments:
            - "@app.paginator.chapter"
            - "@app.paginator.scene"

    app.paginator.chapter:
        class: AppBundle\Pagination\Chapter\ChapterPaginator
        arguments:
            - "@app.repository.chapter"

    # Scene
    app.paginator.aggregate.scene:
        class: AppBundle\Pagination\Scene\SceneAggregate
        arguments:
            - "@app.paginator.scene"
            - "@app.paginator.character"
            - "@app.paginator.item"
            - "@app.paginator.location"
            - "@app.paginator.event"

    app.paginator.scene:
        class: AppBundle\Pagination\Scene\ScenePaginator
        arguments:
            - "@app.repository.scene"

    # Character, Item, Location, Event
    app.paginator.character:
        class: AppBundle\Pagination\CharacterPaginator
        arguments:
            - "@app.repository.character"

    app.paginator.item:
        class: AppBundle\Pagination\ItemPaginator
        arguments:
            - "@app.repository.item"

    app.paginator.location:
        class: AppBundle\Pagination\LocationPaginator
        arguments:
            - "@app.repository.location"

    app.paginator.event:
        class: AppBundle\Pagination\EventPaginator
        arguments:
            - "@app.repository.event"
