---
services:
    # Book
    app.paginator.aggregate.book:
        class: AppBundle\Pagination\Book\BookAggregate
        arguments:
            - "@app.paginator.book"
            - "@app.paginator.chapter"

    app.paginator.book:
        class: AppBundle\Pagination\Book\BookPaginator
        arguments:
            - "@app.repository.book"

    # Chapter
    app.paginator.aggregate.chapter:
        class: AppBundle\Pagination\Chapter\ChapterAggregate
        arguments:
            - "@app.paginator.chapter"
            - "@app.paginator.scene"

    app.paginator.chapter:
        class: AppBundle\Pagination\Chapter\ChapterPaginator
        arguments:
            - "@app.repository.chapter"

    # Scene
    app.paginator.aggregate.scene:
        class: AppBundle\Pagination\Scene\SceneAggregate
        arguments:
            - "@app.paginator.scene"
            - "@app.paginator.character"
            - "@app.paginator.item"
            - "@app.paginator.location"

    app.paginator.scene:
        class: AppBundle\Pagination\Scene\ScenePaginator
        arguments:
            - "@app.repository.scene"

    # Character, Item, Location
    app.paginator.character:
        class: AppBundle\Pagination\CharacterPaginator
        arguments:
            - "@app.repository.character"

    app.paginator.item:
        class: AppBundle\Pagination\ItemPaginator
        arguments:
            - "@app.repository.item"

    app.paginator.location:
        class: AppBundle\Pagination\LocationPaginator
        arguments:
            - "@app.repository.location"
