---
services:
    app.templating.book.create_form:
        class: AppBundle\Templating\Book\CreateView
        arguments:
            - "@templating"

    app.templating.book.edit_form:
        class: AppBundle\Templating\Book\EditView
        arguments:
            - "@templating"
            - "@app.paginator.aggregate.book"
