---
services:
    app.templating.simple_form:
        class: AppBundle\Templating\SimpleFormView
        arguments:
            - "@templating"

    # Book
    app.templating.book.edit_form:
        class: AppBundle\Templating\Book\EditView
        arguments:
            - "@templating"
            - "@app.paginator.book.chapters"

    app.templating.book.list:
        class: AppBundle\Templating\Book\ListView
        arguments:
            - "@templating"
            - "@app.paginator.book"

    app.templating.book.chapters_list:
        class: AppBundle\Templating\Book\ChaptersListView
        arguments:
            - "@templating"
            - "@app.paginator.book.chapters"

    # Chapters
    app.templating.chapter.edit_form:
        class: AppBundle\Templating\Chapter\EditView
        arguments:
            - "@templating"
            - "@app.paginator.chapter.scenes"

    app.templating.chapter.list:
        class: AppBundle\Templating\Chapter\ListView
        arguments:
            - "@templating"
            - "@app.paginator.chapter"
