---
fsi_doctrine_extensions:
    orm:
        default:
            translatable: true
            uploadable: true

knp_menu:
    twig:
        template: menu\knp_menu.html.twig

jms_i18n_routing:
    default_locale: pl
    locales: [pl, en]
    strategy: prefix
