---
fsi_doctrine_extensions:
    orm:
        default:
            translatable: true
            uploadable: true

knp_menu:
    twig:
        template: menu\knp_dropdown.html.twig

jms_i18n_routing:
    default_locale: pl
    locales: [pl, en]
    strategy: prefix

ivory_ck_editor:
    input_sync: true
