imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: true
    profiler:
        only_exceptions: false
        enabled: true
        collect: true

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!event']
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]

swiftmailer:
    logging: true
    disable_delivery: true

doctrine:
    dbal:
        dbname: "%database_name%-tst"

# testing should be done in english
parameters:
    locale: en

fsi_doctrine_extensions:
    default_filesystem_path: '%kernel.root_dir%/../web/uploaded_test'
    default_filesystem_base_url: '/uploaded_test'
