base:
    resource: "@AppBundle/Resources/config/routing/base.yml"
    prefix:   /

# Security
security:
    resource: "@AppBundle/Resources/config/routing/security.yml"
    prefix:   /

# Book
book:
    resource: "@AppBundle/Resources/config/routing/book.yml"
    prefix:   /book
    options:
        expose: true

# Chapter
chapter:
    resource: "@AppBundle/Resources/config/routing/chapter.yml"
    prefix:   /chapter
    options:
        expose: true

# Scene
scene:
    resource: "@AppBundle/Resources/config/routing/scene.yml"
    prefix:   /scene
    options:
        expose: true

# Character
character:
    resource: "@AppBundle/Resources/config/routing/character.yml"
    prefix:   /character
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

# Item
item:
    resource: "@AppBundle/Resources/config/routing/item.yml"
    prefix:   /item
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

# Location
location:
    resource: "@AppBundle/Resources/config/routing/location.yml"
    prefix:   /location
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

# Event
event:
    resource: "@AppBundle/Resources/config/routing/event.yml"
    prefix:   /event
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true
