fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_base:
    resource: "@AppBundle/Resources/config/routing/base.yml"
    prefix:   /

app_scene_standalone:
    resource: "@AppBundle/Resources/config/routing/scene/standalone.yml"
    prefix:   /scene/standalone
    options:
        expose: true

app_scene_character:
    resource: "@AppBundle/Resources/config/routing/scene/character.yml"
    prefix:   /character
    options:
        expose: true

app_scene_item:
    resource: "@AppBundle/Resources/config/routing/scene/item.yml"
    prefix:   /item
    options:
        expose: true

app_scene_location:
    resource: "@AppBundle/Resources/config/routing/scene/location.yml"
    prefix:   /location
    options:
        expose: true
