fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app_base:
    resource: "@AppBundle/Resources/config/routing/base.yml"
    prefix:   /

# Chapter
app_chapter:
    resource: "@AppBundle/Resources/config/routing/chapter.yml"
    prefix:   /chapter
    options:
        expose: true

# Scene
app_scene:
    resource: "@AppBundle/Resources/config/routing/scene.yml"
    prefix:   /scene
    options:
        expose: true

# Character
app_character:
    resource: "@AppBundle/Resources/config/routing/character.yml"
    prefix:   /character
    options:
        expose: true

# Item
app_item:
    resource: "@AppBundle/Resources/config/routing/item.yml"
    prefix:   /item
    options:
        expose: true

# Location
app_location:
    resource: "@AppBundle/Resources/config/routing/location.yml"
    prefix:   /location
    options:
        expose: true
