services:
    _defaults:
        autowire: true
        autoconfigure: true

    SimpleBus\Message\Bus\MessageBus: "@transaction_wrapped_command_bus"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"

    AppBundle\Controller\:
        resource: "../../src/AppBundle/Controller/*"

    AppBundle\Pagination\:
        resource: "../../src/AppBundle/Pagination/*"

    AppBundle\Routing\:
        resource: "../../src/AppBundle/Routing/*"

    AppBundle\Templating\:
        resource: "../../src/AppBundle/Templating/*"

    transaction_wrapped_command_bus:
        class:     AppBundle\Bus\TransactionWrappedBus
        decorates: command_bus
        arguments: ['@transaction_wrapped_command_bus.inner']
        public:    false
