services:
    _defaults:
        autowire: true
        autoconfigure: true

    Knp\Menu\FactoryInterface: "@knp_menu.factory"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"
    SimpleBus\Message\Bus\MessageBus: "@transaction_wrapped_command_bus"
    Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface: '@security.user_password_encoder.generic'

    AppBundle\Controller\:
        resource: "../../src/AppBundle/Controller/*"

    AppBundle\Pagination\:
        resource: "../../src/AppBundle/Pagination/*"

    AppBundle\Routing\:
        resource: "../../src/AppBundle/Routing/*"

    AppBundle\Templating\:
        resource: "../../src/AppBundle/Templating/*"

    AppBundle\Validation\Constraints\:
        resource: "../../src/AppBundle/Validation/Constraints/*"

    # Twig
    AppBundle\Twig\:
        resource: "../../src/AppBundle/Twig/*"
        autowire: true
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    # Menu
    app.menu.builder:
        class: AppBundle\Menu\Builder
        autowire: true

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main }

    AppBundle\JSON\EventParser:
        autowire: true

    # Bus
    transaction_wrapped_command_bus:
        class:     AppBundle\Bus\TransactionWrappedBus
        decorates: command_bus
        arguments: ['@transaction_wrapped_command_bus.inner']
        public:    false

    user_aware_command_bus:
        class:     AppBundle\Bus\UserAwareBus
        decorates: transaction_wrapped_command_bus
        arguments: ['@user_aware_command_bus.inner']
        public:    false

    user_access_command_bus:
        class:     AppBundle\Bus\UserAccessBus
        decorates: user_aware_command_bus
        arguments: ['@user_access_command_bus.inner']
        public:    false

    # Security
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true
