services:
    _defaults:
        autowire: true
        autoconfigure: true

    SimpleBus\Message\Bus\MessageBus: "@transaction_wrapped_command_bus"
    Knp\Menu\FactoryInterface: "@knp_menu.factory"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"

    AppBundle\Controller\:
        resource: "../../src/AppBundle/Controller/*"

    AppBundle\Pagination\:
        resource: "../../src/AppBundle/Pagination/*"

    AppBundle\Routing\:
        resource: "../../src/AppBundle/Routing/*"

    AppBundle\Templating\:
        resource: "../../src/AppBundle/Templating/*"

    # Twig
    AppBundle\Twig\:
        resource: "../../src/AppBundle/Twig/*"
        autowire: true
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    # Menu
    app.menu.builder:
        class: AppBundle\Menu\Builder
        autowire: true

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main }

    AppBundle\JSON\EventParser:
        autowire: true

    # Bus
    transaction_wrapped_command_bus:
        class:     AppBundle\Bus\TransactionWrappedBus
        decorates: command_bus
        arguments: ['@transaction_wrapped_command_bus.inner']
        public:    false
