---
app_index:
    path: /
    controller: AppBundle\Controller\DashboardController
    methods:  GET

alerts:
    path: /alerts
    controller: AppBundle\Controller\AlertsController
    methods:  GET
    condition: "request.isXmlHttpRequest()"
