---
app_book_create:
    path: /create/{page}
    defaults: { _controller: app.controller.book.create:createAction, page: 1 }
    methods:  [GET, POST]

app_book_edit:
    path: /edit/{id}/{page}
    defaults: { _controller: app.controller.book.edit:editAction, page: 1 }
    methods:  [GET, POST]

app_book_list:
    path: /list/{page}
    defaults: { _controller: app.controller.book.list:listAction, page: 1 }
    methods:  GET

app_book_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.book.delete:deleteAction, page: 1 }
    methods:  GET

app_book_chapter_list:
    path: /chapters/{id}/{page}
    defaults: { _controller: app.controller.book.chapters_list:chaptersAction, page: 1 }
    condition: "request.isXmlHttpRequest()"
    methods:  GET
