---
app_book_new:
    path: /new/{page}
    defaults: { _controller: app.controller.book:newAction, page: 1 }
    methods:  [GET, POST]

app_book_edit:
    path: /edit/{id}/{page}
    defaults: { _controller: app.controller.book:editAction, page: 1 }
    methods:  [GET, POST]

app_book_list:
    path: /list/{page}
    defaults: { _controller: app.controller.book:listAction, page: 1 }
    methods:  GET

app_book_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.book:deleteAction, page: 1 }
    methods:  GET
