---
app_chapter_new_standalone:
    path: /new_standalone/{page}
    defaults: { _controller: app.controller.chapter.create:createAction, page: 1 }
    methods:  [GET, POST]

app_chapter_new_assigned:
    path: /new_assigned/{id}
    defaults: { _controller: app.controller.chapter.create_assigned:createAction }
    methods:  [GET, POST]

app_chapter_edit:
    path: /edit/{id}/{page}
    defaults: { _controller: app.controller.chapter.edit:editAction, page: 1 }
    methods:  [GET, POST]

app_chapter_list:
    path: /list/{page}
    defaults: { _controller: app.controller.chapter.list:listAction, page: 1 }
    methods:  GET

app_chapter_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.chapter.delete:deleteAction, page: 1 }
    methods:  GET

app_chapter_scenes_list:
    path: /scenes/{id}/{page}
    defaults: { _controller: app.controller.chapter.list:scenesListAction, page: 1 }
    condition: "request.isXmlHttpRequest()"
    methods:  GET

app_chapter_display:
    path: /display/{id}
    defaults: { _controller: app.controller.chapter.display:displayAction }
    methods:  GET

app_chapter_pdf:
    path: /pdf/{id}
    defaults: { _controller: app.controller.pdf:chapterAction }
    methods:  GET
