---
app_chapter_new:
    path: /new/{book_id}
    defaults: { _controller: app.controller.chapter:newAction, book_id: null }
    methods:  [GET, POST]

app_chapter_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.chapter:editAction }
    methods:  [GET, POST]

app_chapter_list:
    path: /list/{page}
    defaults: { _controller: app.controller.chapter:listAction, page: 1 }
    methods:  GET

app_chapter_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.chapter:deleteAction, page: 1 }
    methods:  GET
