---
app_chapter_new_standalone:
    path: /new_standalone/{page}
    defaults: { _controller: app.controller.chapter.create }
    methods:  [GET, POST]

app_chapter_new_assigned:
    path: /new_assigned/{id}
    defaults: { _controller: app.controller.chapter.create_assigned }
    methods:  [GET, POST]

app_chapter_edit:
    path: /edit/{id}/{page}
    defaults: { _controller: app.controller.chapter.edit }
    methods:  [GET, POST]

app_chapter_list:
    path: /list/{page}
    defaults: { _controller: app.controller.chapter.list, page: 1 }
    methods:  GET

app_chapter_scenes_list:
    path: /scenes/{id}/{page}
    defaults: { _controller: app.controller.chapter.scenes_list, page: 1 }
    condition: "request.isXmlHttpRequest()"
    methods:  GET

app_chapter_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.chapter.delete, page: 1 }
    methods:  GET

app_chapter_display:
    path: /display/{id}
    defaults: { _controller: app.controller.chapter.display }
    methods:  GET

app_chapter_pdf:
    path: /pdf/{id}
    defaults: { _controller: app.controller.pdf:chapterAction }
    methods:  GET
