---
app_character_new:
    path: /new/{id}
    defaults: { _controller: app.controller.character:newAction }
    methods:  [GET, POST]

app_character_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.character:editAction }
    methods:  [GET, POST]

app_character_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.character:listAction, page: 1 }
    methods:  GET

app_character_delete:
    path: /delete/{scene_id}/{character_id}/{page}
    defaults: { _controller: app.controller.character:deleteAction, page: 1 }
    methods:  GET

app_character_display:
    path: /display/{id}
    defaults: { _controller: app.controller.character:displayAction }
    methods:  GET

app_character_related:
    path: /related/{id}/{page}
    defaults: { _controller: app.controller.character:relatedAction, page: 1 }
    methods:  GET

app_character_add_to_scene:
    path: /add-to-scene/{scene_id}/{character_id}
    defaults: { _controller: app.controller.character:addToSceneAction }
    methods:  GET

app_character_remove_from_scene:
    path: /remove-from-scene/{scene_id}/{character_id}/{page}
    defaults: { _controller: app.controller.character:removeFromSceneAction }
    methods:  GET
