---
app_character_new:
    path: /new/{id}
    defaults: { _controller: app.controller.character.create:newAction }
    methods:  [GET, POST]

app_character_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.character.edit:editAction }
    methods:  [GET, POST]

app_character_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.character.list:listAction, page: 1 }
    methods:  GET

app_character_delete:
    path: /delete/{id}
    defaults: { _controller: app.controller.character.delete:deleteAction }
    methods:  GET

app_character_display:
    path: /display/{id}
    defaults: { _controller: app.controller.character.display:displayAction }
    methods:  GET

app_character_related:
    path: /related/{id}/{page}
    defaults: { _controller: app.controller.character.list:relatedAction, page: 1 }
    methods:  GET

app_character_add_to_scene:
    path: /add-to-scene/{scene_id}/{character_id}
    defaults: { _controller: app.controller.character.edit:addToSceneAction }
    methods:  GET

app_character_remove_from_scene:
    path: /remove-from-scene/{scene_id}/{character_id}
    defaults: { _controller: app.controller.character.delete:removeFromSceneAction }
    methods:  GET
