---
app_character_new:
    path: /new/{id}
    defaults: { _controller: app.controller.character:newAction }
    methods:  [GET, POST]

app_character_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.character:editAction }
    methods:  [GET, POST]

app_character_list:
    path: /list/{id}
    defaults: { _controller: app.controller.character:listAction }
    methods:  GET

app_character_delete:
    path: /delete/{scene_id}/{character_id}
    defaults: { _controller: app.controller.character:deleteAction }
    methods:  GET
