list:
    path:     /{elementName}/list
    defaults: { _controller: app.controller.list:listAction }
    methods:  GET

create:
    path:     /{elementName}/create
    defaults: { _controller: app.controller.form:createAction }
    methods:  [GET, POST]

edit:
    path:     /{elementName}/edit/{id}
    defaults: { _controller: app.controller.form:editAction }
    methods:  [GET, PUT]

delete:
    path:     /{elementName}/delete/{id}
    defaults: { _controller: app.controller.form:deleteAction }
    methods:  DELETE
