crud_list:
    path:     /{elementName}/list
    defaults: { _controller: app.controller.list:listAction }
    methods:  GET

crud_create:
    path:     /{elementName}/create
    defaults: { _controller: app.controller.form:createAction }
    methods:  [GET, POST]

crud_edit:
    path:     /{elementName}/{id}/edit
    defaults: { _controller: app.controller.form:editAction }
    methods:  [GET, PUT]

crud_delete:
    path:     /{elementName}/{id}/delete
    defaults: { _controller: app.controller.form:deleteAction }
    methods:  DELETE
