crud_list:
    path:     /{elementName}/list
    defaults: { _controller: app.controller.list:listAction }
    methods:  GET

crud_create:
    path:     /{elementName}/add
    defaults: { _controller: app.controller.form:createAction }
    methods:  [GET, POST]

crud_edit:
    path:     /{elementName}/edit/{id}
    defaults: { _controller: app.controller.form:editAction }
    methods:  [GET, PUT]

crud_delete:
    path:     /{elementName}/delete/{id}
    defaults: { _controller: app.controller.form:deleteAction }
    methods:  DELETE
