---
app_event_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.event.list:listAction, page: 1 }
    methods:  GET

app_event_add:
    path: /event/{id}/{model}
    defaults: { _controller: app.controller.event.create:createAction }
    methods:  [GET, POST]
    requirements:
        model: .+

app_event_delete:
    path: /delete/{id}
    defaults: { _controller: app.controller.event.delete:deleteAction }
    methods:  GET
