---
app_item_new:
    path: /new/{id}
    defaults: { _controller: app.controller.item.create:createAction }
    methods:  [GET, POST]

app_item_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.item.edit:editAction }
    methods:  [GET, POST]

app_item_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.item.list:listAction, page: 1 }
    methods:  GET

app_item_delete:
    path: /delete/{id}
    defaults: { _controller: app.controller.item.delete:deleteAction }
    methods:  GET

app_item_display:
    path: /display/{id}
    defaults: { _controller: app.controller.item:displayAction }
    methods:  GET

app_item_related:
    path: /related/{id}/{page}
    defaults: { _controller: app.controller.item.list:relatedAction, page: 1 }
    methods:  GET

app_item_add_to_scene:
    path: /add-to-scene/{scene_id}/{item_id}
    defaults: { _controller: app.controller.item.edit:addToSceneAction }
    methods:  GET

app_item_remove_from_scene:
    path: /remove-from-scene/{scene_id}/{item_id}
    defaults: { _controller: app.controller.item.delete:removeFromSceneAction }
    methods:  GET
