---
app_item_new:
    path: /new/{id}
    defaults: { _controller: app.controller.item:newAction }
    methods:  [GET, POST]

app_item_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.item:editAction }
    methods:  [GET, POST]

app_item_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.item:listAction, page: 1 }
    methods:  GET

app_item_delete:
    path: /delete/{scene_id}/{item_id}/{page}
    defaults: { _controller: app.controller.item:deleteAction, page: 1 }
    methods:  GET

app_item_display:
    path: /display/{id}
    defaults: { _controller: app.controller.item:displayAction }
    methods:  GET

app_item_related:
    path: /related/{id}/{page}
    defaults: { _controller: app.controller.item:relatedAction, page: 1 }
    methods:  GET

app_item_add_to_scene:
    path: /add-to-scene/{scene_id}/{item_id}
    defaults: { _controller: app.controller.item:addToSceneAction }
    methods:  GET
