---
app_location_new:
    path: /new/{id}
    defaults: { _controller: app.controller.location:newAction }
    methods:  [GET, POST]

app_location_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.location:editAction }
    methods:  [GET, POST]

app_location_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.location:listAction, page: 1 }
    methods:  GET

app_location_delete:
    path: /delete/{scene_id}/{location_id}/{page}
    defaults: { _controller: app.controller.location:deleteAction, page: 1 }
    methods:  GET

app_location_display:
    path: /display/{id}
    defaults: { _controller: app.controller.location:displayAction }
    methods:  GET

app_location_related:
    path: /related/{id}/{page}
    defaults: { _controller: app.controller.location:relatedAction, page: 1 }
    methods:  GET

app_location_add_to_scene:
    path: /add-to-scene/{scene_id}/{location_id}
    defaults: { _controller: app.controller.location:addToSceneAction }
    methods:  GET
