---
app_location_new:
    path: /new/{id}
    defaults: { _controller: app.controller.location:newAction }
    methods:  [GET, POST]

app_location_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.location:editAction }
    methods:  [GET, POST]

app_location_list:
    path: /list/{id}/{page}
    defaults: { _controller: app.controller.location:listAction, page: 1 }
    methods:  GET

app_location_delete:
    path: /delete/{scene_id}/{location_id}/{page}
    defaults: { _controller: app.controller.location:deleteAction, page: 1 }
    methods:  GET
