---
app_scene_new:
    path: /new/{chapter_id}
    defaults: { _controller: app.controller.scene:newAction, chapter_id: null }
    methods:  [GET, POST]

app_scene_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.scene:editAction }
    methods:  [GET, POST]

app_scene_list:
    path: /list/{page}
    defaults: { _controller: app.controller.scene:listAction, page: 1 }
    methods:  GET

app_scene_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.scene:deleteAction, page: 1 }
    methods:  GET
