---
app_scene_new:
    path: /new
    defaults: { _controller: app.controller.scene:newAction }
    methods:  [GET, POST]

app_scene_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.scene:editAction }
    methods:  [GET, POST]
