---
# Standalone
app_standalone_scene_new:
    path: /standalone/new
    defaults: { _controller: app.controller.scene.standalone:newAction }
    methods:  [GET, POST]

app_standalone_scene_edit:
    path: /standalone/edit/{id}
    defaults: { _controller: app.controller.scene.standalone:editAction }
    methods:  [GET, POST]

app_standalone_scene_list:
    path: /standalone/list/{page}
    defaults: { _controller: app.controller.scene.standalone:listAction, page: 1 }
    methods:  GET

app_standalone_scene_delete:
    path: /character/delete/{id}/{page}
    defaults: { _controller: app.controller.scene.standalone:deleteAction, page: 1 }
    methods:  GET

# Character
app_scene_character_new:
    path: /character/new/{id}
    defaults: { _controller: app.controller.scene.character:newAction }
    methods:  [GET, POST]

app_scene_character_edit:
    path: /character/edit/{id}
    defaults: { _controller: app.controller.scene.character:editAction }
    methods:  [GET, POST]

app_scene_character_list:
    path: /character/list/{id}
    defaults: { _controller: app.controller.scene.character:listAction }
    methods:  GET

app_scene_character_delete:
    path: /character/delete/{scene_id}/{character_id}
    defaults: { _controller: app.controller.scene.character:deleteAction }
    methods:  GET
