---
app_scene_new_standalone:
    path: /new-standalone/{page}
    defaults: { _controller: app.controller.scene:newStandaloneAction, page: 1 }
    methods:  [GET, POST]

app_scene_new_assigned:
    path: /new-assigned/{id}
    defaults: { _controller: app.controller.scene:newAssignedAction }
    methods:  [GET, POST]

app_scene_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.scene:editAction }
    methods:  [GET, POST]

app_scene_list:
    path: /list/{page}
    defaults: { _controller: app.controller.scene:listAction, page: 1 }
    methods:  GET

app_scene_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.scene:deleteAction, page: 1 }
    methods:  GET

app_scene_display:
    path: /display/{id}
    defaults: { _controller: app.controller.display:sceneAction }
    methods:  GET

app_scene_pdf:
    path: /pdf/{id}
    defaults: { _controller: app.controller.pdf:sceneAction }
    methods:  GET

app_scene_event:
    path: /event/{id}/{model}
    defaults: { _controller: app.controller.event:formAction }
    methods:  [GET, POST]
    requirements:
        model: .+
