---
login:
    path: /login
    defaults: { _controller: AppBundle\Controller\Security\LoginController }
    methods:  GET|POST

register:
    path: /registration
    defaults: { _controller: AppBundle\Controller\Security\RegisterController }
    methods:  GET|POST

activation:
    path: /activate/{code}
    defaults: { _controller: AppBundle\Controller\Security\ActivationController }
    methods:  GET

password_reset_request:
    path: /reset-password/request
    defaults: { _controller: AppBundle\Controller\Security\ResetPasswordRequestController }
    methods:  GET|POST

password_reset_change:
    path: /reset-password/change/{code}
    defaults: { _controller: AppBundle\Controller\Security\ResetPasswordChangeController }
    methods:  GET|POST

logout:
    path: /logout
    methods:  GET
    options: { i18n: false }
