---
app_scene_location_new:
    path: /location/new/{id}
    defaults: { _controller: app.controller.scene.location:newAction }
    methods:  [GET, POST]

app_scene_location_edit:
    path: /location/edit/{id}
    defaults: { _controller: app.controller.scene.location:editAction }
    methods:  [GET, POST]

app_scene_location_list:
    path: /location/list/{id}
    defaults: { _controller: app.controller.scene.location:listAction }
    methods:  GET

app_scene_location_delete:
    path: /location/delete/{scene_id}/{location_id}
    defaults: { _controller: app.controller.scene.location:deleteAction }
    methods:  GET
