---
paths:
  - ./src
exclude_files: ~
layers:
  - name: Application
    collectors:
      - type: className
        regex: Talesweaver\\Application\\.*
  - name: Doctrine
    collectors:
      - type: className
        regex: Talesweaver\\Doctrine\\.*
  - name: Domain
    collectors:
      - type: className
        regex: Talesweaver\\Domain\\.*
  - name: Integration
    collectors:
      - type: className
        regex: Talesweaver\\Integration\\.*
  - name: Tests
    collectors:
      - type: className
        regex: Talesweaver\\Tests\\.*
ruleset:
  Application:
    - Domain
  Doctrine:
    - Domain
  Domain: ~
  Integration:
    - Application
    - Doctrine
    - Domain
  Tests:
    - Application
    - Domain
    - Doctrine
    - Integration
