# Base
base:
    resource: "routes/base.yml"
    prefix:
        en: /en
        pl: /pl

sort:
    path: /sort/{list}/{direction}/{field}/{redirect}
    controller: Talesweaver\Application\Controller\SortController
    methods: GET
    requirements:
        direction: asc|desc
        redirect: .+

# Security
security:
    resource: "routes/security.yml"
    prefix:
        en: /en
        pl: /pl

# Book
book:
    resource: "routes/book.yml"
    prefix:
        en: /en/book
        pl: /pl/book
    options:
        expose: true

# Chapter
chapter:
    resource: "routes/chapter.yml"
    prefix:
        en: /en/chapter
        pl: /pl/chapter
    options:
        expose: true

# Scene
scene:
    resource: "routes/scene.yml"
    prefix:
        en: /en/scene
        pl: /pl/scene
    options:
        expose: true

# Character
character:
    resource: "routes/character.yml"
    prefix:
        en: /en/character
        pl: /pl/character
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

# Item
item:
    resource: "routes/item.yml"
    prefix:
        en: /en/item
        pl: /pl/item
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

# Location
location:
    resource: "routes/location.yml"
    prefix:
        en: /en/location
        pl: /pl/location
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

# Event
event:
    resource: "routes/event.yml"
    prefix:
        en: /en/event
        pl: /pl/event
    condition: "request.isXmlHttpRequest()"
    options:
        expose: true

publication:
    resource: "routes/publication.yml"
    prefix:
        en: /en/publication
        pl: /pl/publication
    options:
        expose: true

logout:
    path: /logout
    methods:  GET

admin:
    resource: 'routes/admin.yml'
    prefix: /administration
