parameters:
    locale: pl
    mailer_from: "%env(resolve:MAILER_FROM)%"

imports:
    - { resource: services/doctrine.yaml }
    - { resource: services/messages.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $environment: "%kernel.environment%"
            $mailerFrom: "%mailer_from%"

    Knp\Menu\FactoryInterface: "@knp_menu.factory"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"
    SimpleBus\Message\Bus\MessageBus: "@transaction_wrapped_command_bus"
    Symfony\Component\HttpFoundation\Session\Session: "@session"
    Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface: '@security.user_password_encoder.generic'

    Integration\Controller\:
        resource: "../src/Integration/Controller/*"
        public: true

    Integration\DataFixtures\ORM\:
        resource: "../src/Integration/DataFixtures/ORM/*"
        tags: ['doctrine.fixture.orm']

    Integration\:
        resource: "../src/Integration/{Form,JSON,Mail,Menu,Pagination,Routing,Templating,Timeline,Security,Validation}/*"
        exclude: "../src/Integration/Security/function/*"

    # Do not remove, because it is not explicitly used and is removed from the container
    Integration\JSON\EventParser:
        public: true

    # Menu
    app.menu.builder:
        class: Integration\Menu\Builder

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main }

    # Bus
    transaction_wrapped_command_bus:
        class:     Integration\Bus\TransactionWrappedBus
        decorates: command_bus
        arguments: ['@transaction_wrapped_command_bus.inner']

    user_aware_command_bus:
        class:     Integration\Bus\UserAwareBus
        decorates: transaction_wrapped_command_bus
        arguments: ['@user_aware_command_bus.inner']

    user_access_command_bus:
        class:     Integration\Bus\UserAccessBus
        decorates: user_aware_command_bus
        arguments: ['@user_access_command_bus.inner']

    messages_aware_bus:
        class:     Integration\Bus\MessagesAwareBus
        decorates: user_access_command_bus
        arguments: ['@messages_aware_bus.inner']

    # Security
    app.security.login_form_authenticator:
        class: Integration\Security\LoginFormAuthenticator

    Integration\Security\Request\SecuredInstanceParamConverter:
        arguments: [[]]
        autowire: false
        autoconfigure: false
        tags:
            - { name: request.param_converter, priority: 10 }
