parameters:
    locale: pl
    mailer_from: "%env(resolve:MAILER_FROM)%"

imports:
    - { resource: services/doctrine.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $environment: "%kernel.environment%"
            $mailerFrom: "%mailer_from%"
            $newAuthorMailer: '@Talesweaver\Integration\Symfony\Mail\RegistrationMailer'
            $passwordResetMailer: '@Talesweaver\Integration\Symfony\Mail\PasswordResetMailer'

    Knp\Menu\FactoryInterface: "@knp_menu.factory"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"
    Talesweaver\Application\Bus\CommandBus: '@Talesweaver\Integration\Symfony\Bus\CommandBus'
    Talesweaver\Application\Bus\QueryBus: '@Talesweaver\Integration\Symfony\Bus\QueryBus'
    Talesweaver\Application\Form\FormHandlerFactoryInterface: '@Talesweaver\Integration\Symfony\Form\FormHandlerFactory'
    Talesweaver\Application\Http\HtmlContent: '@Talesweaver\Integration\Symfony\Http\HtmlContent'
    Talesweaver\Application\Http\ResponseFactoryInterface: '@Talesweaver\Integration\Symfony\Http\ResponseFactory'
    Talesweaver\Application\Http\UrlGenerator: '@Talesweaver\Integration\Symfony\Http\UrlGenerator'
    Talesweaver\Application\Security\AuthorContext: '@Talesweaver\Integration\Symfony\Security\AuthorContext'
    Talesweaver\Application\Security\AuthenticationContext: '@Talesweaver\Integration\Symfony\Security\AuthenticationContext'
    Talesweaver\Domain\Authors: '@Talesweaver\Integration\Doctrine\Repository\AuthorRepository'
    Talesweaver\Domain\Books: '@Talesweaver\Integration\Symfony\Repository\BookRepository'
    Talesweaver\Domain\Chapters: '@Talesweaver\Integration\Symfony\Repository\ChapterRepository'
    Talesweaver\Domain\Characters: '@Talesweaver\Integration\Symfony\Repository\CharacterRepository'
    Talesweaver\Domain\Events: '@Talesweaver\Integration\Symfony\Repository\EventRepository'
    Talesweaver\Domain\Items: '@Talesweaver\Integration\Symfony\Repository\ItemRepository'
    Talesweaver\Domain\Locations: '@Talesweaver\Integration\Symfony\Repository\LocationRepository'
    Talesweaver\Domain\Scenes: '@Talesweaver\Integration\Symfony\Repository\SceneRepository'
    Talesweaver\Domain\PasswordResetTokens: '@Talesweaver\Integration\Doctrine\Repository\PasswordResetTokenRepository'
    Symfony\Component\Form\Util\ServerParams: "@form.server_params"
    Symfony\Component\HttpFoundation\Session\Session: '@session'
    Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface: '@security.user_password_encoder.generic'

    # Bus
    Talesweaver\Integration\Symfony\Bus\CommandBus:
        arguments:
            $messenger: '@messenger.bus.commands'

    Talesweaver\Integration\Symfony\Bus\QueryBus:
        arguments:
            $messenger: '@messenger.bus.queries'

    Talesweaver\Application\Command\:
        resource: "../src/Application/Command/{Book,Chapter,Character,Event,Item,Location,Scene}/*/CommandHandler.php"

    Talesweaver\Application\Command\Security\:
        resource: "../src/Application/Command/Security/*Handler.php"

    Talesweaver\Application\Query\:
        resource: "../src/Application/Query/{Book,Chapter,Character,Item}/*Handler.php"

    # Resources
    Talesweaver\Integration\Symfony\Controller\:
        resource: "../src/Integration/Symfony/Controller/*"
        public: true

    Talesweaver\Integration\Doctrine\DataFixtures\ORM\:
        resource: "../src/Integration/Doctrine/DataFixtures/ORM/*"
        tags: ['doctrine.fixture.orm']

    Talesweaver\Integration\Symfony\:
        resource: "../src/Integration/Symfony/{Bus/Middleware,Form/Type,Http,JSON,Mail,Menu,Pagination,Timeline,Security,Session,Validation}/*"
        exclude: "../src/Integration/Symfony/Security/function/*"

    # Do not remove, because it is not explicitly used and is removed from the container
    Talesweaver\Integration\Symfony\JSON\EventParser:
        public: true

    # Menu
    app.menu.builder:
        class: Talesweaver\Integration\Symfony\Menu\Builder

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main }

    # Doctrine Extensions
    fsi_doctrine_extensions.filehandler.chain:
        class: Talesweaver\Integration\DoctrineExtensions\Uploadable\FileHandler\DomainFileHandler
        arguments:
            $handlers:
                - "@fsi_doctrine_extensions.filehandler.gaufrette"
                - "@fsi_doctrine_extensions.filehandler.symfony_uploaded_file"
                - "@fsi_doctrine_extensions.filehandler.splfileinfo"

    # Form
    Talesweaver\Integration\Symfony\Form\FormClassResolver: ~
    Talesweaver\Integration\Symfony\Form\FormHandlerFactory: ~
    Talesweaver\Integration\Symfony\Form\Psr7FormRequestHandler: ~
    Talesweaver\Integration\Symfony\Form\TypeExtension\Psr7Extension:
        tags: [{ name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType, priority: -1 }]
    Talesweaver\Integration\Symfony\Form\TypeExtension\Psr7FileExtension:
        tags: [{ name: form.type_extension, extended_type: FSi\Bundle\DoctrineExtensionsBundle\Form\Type\FSi\FileType, priority: -1 }]

    # Security
    app.security.login_form_authenticator:
        class: Talesweaver\Integration\Symfony\Security\LoginFormAuthenticator

    Talesweaver\Integration\Symfony\Security\Request\SecuredInstanceParamConverter:
        arguments: [[]]
        autowire: false
        autoconfigure: false
        tags:
            - { name: request.param_converter, priority: 10 }

    # Session
    Talesweaver\Application\Session\FlashBag:
        alias: Talesweaver\Integration\Symfony\Session\FlashBag

    Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface:
        factory: ["@session", getFlashBag]
        lazy: true
