parameters:
    locale: pl
    mailer_from: "%env(resolve:MAILER_FROM)%"

imports:
    - { resource: services/doctrine.yaml }
    - { resource: services/messages.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $environment: '%kernel.environment%'

    Knp\Menu\FactoryInterface: "@knp_menu.factory"
    Knp\Snappy\GeneratorInterface: "@knp_snappy.pdf"
    SimpleBus\Message\Bus\MessageBus: "@transaction_wrapped_command_bus"
    Symfony\Component\HttpFoundation\Session\Session: "@session"
    Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface: '@security.user_password_encoder.generic'

    App\Controller\:
        resource: "../src/App/Controller/*"
        public: true

    App\DataFixtures\ORM\:
        resource: "../src/App/DataFixtures/ORM/*"
        tags: ['doctrine.fixture.orm']

    App\Mail\PasswordResetMailer:
        arguments:
            $mailerFrom: "%mailer_from%"

    App\Mail\RegistrationMailer:
        arguments:
            $mailerFrom: "%mailer_from%"

    App\:
        resource: "../src/App/{Form,JSON,Menu,Pagination,Routing,Templating,Timeline,Security,Validation}/*"
        exclude: "../src/App/Security/function/*"

    # Do not remove, because it is not explicitly used and is removed from the container
    App\JSON\EventParser:
        public: true

    # Menu
    app.menu.builder:
        class: App\Menu\Builder

    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu.builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main }

    # Bus
    transaction_wrapped_command_bus:
        class:     App\Bus\TransactionWrappedBus
        decorates: command_bus
        arguments: ['@transaction_wrapped_command_bus.inner']

    user_aware_command_bus:
        class:     App\Bus\UserAwareBus
        decorates: transaction_wrapped_command_bus
        arguments: ['@user_aware_command_bus.inner']

    user_access_command_bus:
        class:     App\Bus\UserAccessBus
        decorates: user_aware_command_bus
        arguments: ['@user_access_command_bus.inner']

    messages_aware_bus:
        class:     App\Bus\MessagesAwareBus
        decorates: user_access_command_bus
        arguments: ['@messages_aware_bus.inner']

    # Security
    app.security.login_form_authenticator:
        class: App\Security\LoginFormAuthenticator

    App\Security\Request\SecuredInstanceParamConverter:
        arguments: [[]]
        autowire: false
        autoconfigure: false
        tags:
            - { name: request.param_converter, priority: 10 }
