---
columns:
    name:
        type: text
    actions:
        type: action
        options:
            label: Usuń
            field_mapping: ['id']
            actions:
                edit:
                    route_name: edit
                    additional_parameters: { elementName: chapter }
                    parameters_field_mapping: {'id': 'id'}
                delete:
                    route_name: delete
                    additional_parameters: { elementName: chapter }
                    parameters_field_mapping: {'id': 'id'}
