---
columns:
    title:
        type: text
        options:
            label: section.title
    actions:
        type: action
        options:
            label: list.actions
            field_mapping: ['id']
            actions:
                edit:
                    route_name: edit
                    additional_parameters: { elementName: paragraph }
                    parameters_field_mapping: {'id': 'id'}
                delete:
                    route_name: delete
                    additional_parameters: { elementName: paragraph }
                    parameters_field_mapping: {'id': 'id'}
