---
app_chapter_scene_new:
    path: /scene/new/{id}
    defaults: { _controller: app.controller.chapter.scene:newAction }
    methods:  [GET, POST]

app_chapter_scene_edit:
    path: /scene/edit/{id}
    defaults: { _controller: app.controller.chapter.scene:editAction }
    methods:  [GET, POST]

app_chapter_scene_list:
    path: /scene/list/{id}
    defaults: { _controller: app.controller.chapter.scene:listAction }
    methods:  GET

app_chapter_scene_delete:
    path: /scene/delete/{chapter_id}/{scene_id}
    defaults: { _controller: app.controller.chapter.scene:deleteAction }
    methods:  GET
