---
app_standalone_chapter_new:
    path: /new
    defaults: { _controller: app.controller.chapter.standalone:newAction }
    methods:  [GET, POST]

app_standalone_chapter_edit:
    path: /edit/{id}
    defaults: { _controller: app.controller.chapter.standalone:editAction }
    methods:  [GET, POST]

app_standalone_chapter_list:
    path: /list/{page}
    defaults: { _controller: app.controller.chapter.standalone:listAction, page: 1 }
    methods:  GET

app_standalone_chapter_delete:
    path: /delete/{id}/{page}
    defaults: { _controller: app.controller.chapter.standalone:deleteAction, page: 1 }
    methods:  GET
