---
Talesweaver\Application\Book\Create\DTO:
    constraints:
        - Talesweaver\Integration\Symfony\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title' }
            repositoryMethod: entityExists
            path: title
            entityClass: Talesweaver\Domain\Book
            message: book.exists
    properties:
        title:
            - NotBlank: ~

Talesweaver\Application\Book\Edit\DTO:
    constraints:
        - Talesweaver\Integration\Symfony\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title' }
            id: id
            repositoryMethod: entityExists
            path: title
            entityClass: Talesweaver\Domain\Book
            message: book.exists
    properties:
        title:
            - NotBlank: ~
