---
Talesweaver\Application\Chapter\Create\DTO:
    constraints:
        - Talesweaver\Integration\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title', book: 'e.book' }
            repositoryMethod: entityExists
            path: title
            entityClass: Talesweaver\Domain\Chapter
            message: chapter.exists
    properties:
        title:
            - NotBlank: ~

Talesweaver\Application\Chapter\Edit\DTO:
    constraints:
        - Talesweaver\Integration\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title', book: 'e.book' }
            id: id
            repositoryMethod: entityExists
            path: title
            entityClass: Talesweaver\Domain\Chapter
            message: chapter.exists
    properties:
        title:
            - NotBlank: ~
