---
Application\Chapter\Create\DTO:
    constraints:
        - App\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title', book: 'e.book' }
            repositoryMethod: entityExists
            path: title
            entityClass: Domain\Chapter
            message: chapter.exists
    properties:
        title:
            - NotBlank: ~

Application\Chapter\Edit\DTO:
    constraints:
        - App\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title', book: 'e.book' }
            id: id
            repositoryMethod: entityExists
            path: title
            entityClass: Domain\Chapter
            message: chapter.exists
    properties:
        title:
            - NotBlank: ~
