---
Talesweaver\Application\Character\Create\DTO:
    constraints:
        - Talesweaver\Integration\Symfony\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scene: 'e.scenes' }
            repositoryMethod: entityExists
            path: name
            entityClass: Talesweaver\Domain\Character
            message: character.exists
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~

Talesweaver\Application\Character\Edit\DTO:
    constraints:
        - Talesweaver\Integration\Symfony\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scenes: 'e.scenes' }
            id: id
            repositoryMethod: entityExists
            path: name
            entityClass: Talesweaver\Domain\Character
            message: character.exists
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~
