---
Application\Event\Create\DTO:
    constraints:
        - Integration\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scene: 'e.scene' }
            repositoryMethod: entityExists
            path: name
            entityClass: Domain\Event
            message: event.exists
    properties:
        name:
            - NotBlank: ~
        model:
            - NotBlank: ~
            - Valid: ~
        scene:
            - NotBlank: ~

Application\Event\Edit\DTO:
    constraints:
        - Integration\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scene: 'e.scene' }
            repositoryMethod: entityExists
            id: id
            path: name
            entityClass: Domain\Event
            message: event.exists
    properties:
        name:
            - NotBlank: ~
        model:
            - NotBlank: ~
            - Valid: ~

Domain\Event\Meeting:
    constraints:
        - Integration\Validation\Constraints\Meeting: ~
    properties:
        root:
            - NotBlank: ~
        location:
            - NotBlank: ~
        relation:
            - NotBlank: ~
