---
Application\Item\Create\DTO:
    constraints:
        - Integration\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scene: 'e.scenes' }
            repositoryMethod: entityExists
            path: name
            entityClass: Domain\Item
            message: item.exists
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~

Application\Item\Edit\DTO:
    constraints:
        - Integration\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scenes: 'e.scenes' }
            id: id
            repositoryMethod: entityExists
            path: name
            entityClass: Domain\Item
            message: item.exists
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~
