---
Domain\Item\Create\DTO:
    constraints:
        - App\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scene: 'e.scenes' }
            repositoryMethod: entityExists
            path: name
            entityClass: App\Entity\Item
            message: item.exists
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~

Domain\Item\Edit\DTO:
    constraints:
        - App\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scenes: 'e.scenes' }
            id: id
            repositoryMethod: entityExists
            path: name
            entityClass: App\Entity\Item
            message: item.exists
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~
