---
Talesweaver\Application\Scene\Create\DTO:
    constraints:
        - Talesweaver\Integration\Symfony\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title', chapter: 'e.chapter' }
            repositoryMethod: entityExists
            path: title
            entityClass: Talesweaver\Domain\Scene
            message: scene.exists
    properties:
        title:
            - NotBlank: ~

Talesweaver\Application\Scene\Edit\DTO:
    constraints:
        - Talesweaver\Integration\Symfony\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title', chapter: 'e.chapter' }
            id: id
            repositoryMethod: entityExists
            path: title
            entityClass: Talesweaver\Domain\Scene
            message: scene.exists
    properties:
        title:
            - NotBlank: ~
