---
AppBundle\Entity\Book:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\TranslatableRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        chapters:
            targetEntity: AppBundle\Entity\Chapter
            mappedBy: book
            cascade: [persist]
        translations:
            targetEntity: AppBundle\Entity\Translation\BookTranslation
            mappedBy: book
            indexBy: locale
            cascade: [persist, remove]
