---
AppBundle\Entity\Book:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\BookRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        chapters:
            targetEntity: AppBundle\Entity\Chapter
            mappedBy: book
            cascade: [persist]
        translations:
            targetEntity: AppBundle\Entity\Translation\BookTranslation
            mappedBy: book
            indexBy: locale
            cascade: [persist, remove]
