---
AppBundle\Entity\Chapter:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\ChapterRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        scenes:
            targetEntity: AppBundle\Entity\Scene
            mappedBy: chapter
            cascade: [persist]
        translations:
            targetEntity: AppBundle\Entity\Translation\ChapterTranslation
            mappedBy: chapter
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        book:
            targetEntity: AppBundle\Entity\Book
            inversedBy: chapters
            joinColumn:
                onDelete: "CASCADE"
