---
AppBundle\Entity\Character:
    type: entity
    table: character_entity
    repositoryClass: AppBundle\Entity\Repository\CharacterRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        avatarKey:
            type: text
            nullable: true
            fsi: { uploadable: { targetField: avatar } }
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\CharacterTranslation
            mappedBy: character
            indexBy: locale
            cascade: [persist, remove]
    manyToMany:
        scenes:
            targetEntity: AppBundle\Entity\Scene
            mappedBy: characters
        items:
            targetEntity: AppBundle\Entity\Item
            inversedBy: characters
        locations:
            targetEntity: AppBundle\Entity\Location
            inversedBy: characters
