---
AppBundle\Entity\Character:
    type: entity
    table: character_entity
    repositoryClass: AppBundle\Repository\CharacterRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fsi:
        translatable:
            locale: locale
            fields:
                name:
                    mappedBy: translations
                    targetField: name
                description:
                    mappedBy: translations
                    targetField: description
    fields:
        avatarKey:
            type: text
            nullable: true
            fsi: { uploadable: { targetField: avatar } }
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\CharacterTranslation
            mappedBy: character
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        book:
            targetEntity: AppBundle\Entity\Book
            joinColumn:
                onDelete: CASCADE
        createdBy:
            targetEntity:  AppBundle\Entity\User
            joinColumn:
                onDelete: CASCADE
    manyToMany:
        chapters:
            targetEntity: AppBundle\Entity\Chapter
            mappedBy: characters
        scenes:
            targetEntity: AppBundle\Entity\Scene
            mappedBy: characters
        items:
            targetEntity: AppBundle\Entity\Item
            inversedBy: characters
        locations:
            targetEntity: AppBundle\Entity\Location
            inversedBy: characters
