---
AppBundle\Entity\Character:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\TranslatableRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\CharacterTranslation
            mappedBy: character
            indexBy: locale
            cascade: [persist, remove]
    manyToMany:
        scenes:
            targetEntity: AppBundle\Entity\Scene
            mappedBy: characters
