---
AppBundle\Entity\Event:
    type: entity
    table: event_entity
    repositoryClass: AppBundle\Entity\Repository\EventRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fsi:
        translatable:
            locale: locale
            fields:
                name:
                    mappedBy: translations
                    targetField: name
    fields:
        model:
            type: json_array
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\EventTranslation
            mappedBy: event
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        scene:
            targetEntity: AppBundle\Entity\Scene
