---
AppBundle\Entity\Location:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\LocationRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fsi:
        translatable:
            locale: locale
            fields:
                name:
                    mappedBy: translations
                    targetField: name
                description:
                    mappedBy: translations
                    targetField: description
    fields:
        avatarKey:
            type: text
            nullable: true
            fsi: { uploadable: { targetField: avatar } }
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\LocationTranslation
            mappedBy: location
            indexBy: locale
            cascade: [persist, remove]
    manyToMany:
        scenes:
            targetEntity: AppBundle\Entity\Scene
            mappedBy: locations
        characters:
            targetEntity: AppBundle\Entity\Character
            mappedBy: locations
        items:
            targetEntity: AppBundle\Entity\Item
            inversedBy: locations
