---
AppBundle\Entity\Location:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\LocationRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        avatarKey:
            type: text
            nullable: true
            fsi: { uploadable: { targetField: avatar } }
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\LocationTranslation
            mappedBy: location
            indexBy: locale
            cascade: [persist, remove]
    manyToMany:
        scenes:
            targetEntity: AppBundle\Entity\Scene
            mappedBy: locations
