---
AppBundle\Entity\Paragraph:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\TranslatableRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\ParagraphTranslation
            mappedBy: paragraph
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        chapter:
            targetEntity: AppBundle\Entity\Chapter
            inversedBy: paragraphs
