---
AppBundle\Entity\Scene:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\SceneRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fsi:
        translatable:
            locale: locale
            fields:
                title:
                    mappedBy: translations
                    targetField: title
                text:
                    mappedBy: translations
                    targetField: text
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\SceneTranslation
            mappedBy: scene
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        chapter:
            targetEntity: AppBundle\Entity\Chapter
            inversedBy: scenes
            joinColumn:
                onDelete: "CASCADE"
        createdBy:
            targetEntity:  AppBundle\Entity\User
    manyToMany:
        characters:
            targetEntity: AppBundle\Entity\Character
            inversedBy: scenes
            cascade: [persist]
        items:
            targetEntity: AppBundle\Entity\Item
            inversedBy: scenes
            cascade: [persist]
        locations:
            targetEntity: AppBundle\Entity\Location
            inversedBy: scenes
            cascade: [persist]
