---
AppBundle\Entity\Scene:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\TranslatableRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\SceneTranslation
            mappedBy: scene
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        chapter:
            targetEntity: AppBundle\Entity\Chapter
            inversedBy: scenes
            joinColumn:
                onDelete: "SET NULL"
