---
AppBundle\Entity\Scene:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\SceneRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\SceneTranslation
            mappedBy: scene
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        chapter:
            targetEntity: AppBundle\Entity\Chapter
            inversedBy: scenes
            joinColumn:
                onDelete: "CASCADE"
    manyToMany:
        characters:
            targetEntity: AppBundle\Entity\Character
            inversedBy: scenes
            cascade: [persist]
        items:
            targetEntity: AppBundle\Entity\Item
            inversedBy: scenes
            cascade: [persist]
        locations:
            targetEntity: AppBundle\Entity\Location
            inversedBy: scenes
            cascade: [persist]
