---
AppBundle\Entity\Section:
    type: entity
    repositoryClass: AppBundle\Entity\Repository\TranslatableRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
    oneToMany:
        translations:
            targetEntity: AppBundle\Entity\Translation\SectionTranslation
            mappedBy: section
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        chapter:
            targetEntity: AppBundle\Entity\Chapter
            inversedBy: sections
