---
AppBundle\Entity\Translation\LocationTranslation:
    type: entity
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        description:
            type: text
            nullable: true
        locale:
            type: string
            length: 2
            fsi:
                translatable:
                    locale: ~
    manyToOne:
        location:
            targetEntity: AppBundle\Entity\Location
            inversedBy: translations
            joinColumn:
                onDelete: "CASCADE"
