---
AppBundle\Entity\User:
    type: entity
    table: app_user
    repositoryClass: AppBundle\Repository\Doctrine\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            unique: true
        password: ~
    manyToMany:
        roles:
            targetEntity: AppBundle\Entity\UserRole
            joinTable:
                name: user_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: role
