---
AppBundle\Entity\User\PasswordResetToken:
    type: entity
    repositoryClass: AppBundle\Repository\Doctrine\PasswordResetTokenRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        value: ~
        active:
            type: boolean
        createdAt:
            type: datetime_immutable
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: passwordResetTokens
            joinColumn:
                onDelete: "CASCADE"
