---
AppBundle\Entity\User:
    type: entity
    table: app_user
    repositoryClass: AppBundle\Entity\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username: ~
        password: ~
        salt: ~
    manyToMany:
        roles:
            targetEntity: AppBundle\Entity\UserRole
            joinTable:
                name: user_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: role
