---
AppBundle\Entity\User:
    type: entity
    table: app_user
    repositoryClass: AppBundle\Repository\Doctrine\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            unique: true
        password: ~
        active:
            type: boolean
    oneToMany:
        activationCodes:
            targetEntity: AppBundle\Entity\UserActivationCode
            mappedBy: user
            cascade: ["persist", "remove"]
            orderBy:
                createdAt: DESC
    manyToMany:
        roles:
            targetEntity: AppBundle\Entity\UserRole
            joinTable:
                name: user_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: role
