---
Domain\Entity\Chapter:
    type: entity
    repositoryClass: App\Repository\Doctrine\ChapterRepository
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fsi:
        translatable:
            locale: locale
            fields:
                title:
                    mappedBy: translations
                    targetField: title
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    oneToMany:
        scenes:
            targetEntity: Domain\Entity\Scene
            mappedBy: chapter
            cascade: [persist]
        translations:
            targetEntity: Domain\Entity\Translation\ChapterTranslation
            mappedBy: chapter
            indexBy: locale
            cascade: [persist, remove]
    manyToMany:
        characters:
            targetEntity: Domain\Entity\Character
            inversedBy: chapters
    manyToOne:
        book:
            targetEntity: Domain\Entity\Book
            inversedBy: chapters
            joinColumn:
                onDelete: "CASCADE"
        createdBy:
            targetEntity:  Domain\Entity\User
            joinColumn:
                onDelete: CASCADE
