---
Domain\Entity\Event:
    type: entity
    table: event_entity
    repositoryClass: App\Repository\Doctrine\EventRepository
    entityListeners:
        App\JSON\ModelParserListener: ~
    id:
        id:
            type: uuid
            generator: { strategy: NONE }
    fsi:
        translatable:
            locale: locale
            fields:
                name:
                    mappedBy: translations
                    targetField: name
    fields:
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
        model:
            type: json_array
    oneToMany:
        translations:
            targetEntity: Domain\Entity\Translation\EventTranslation
            mappedBy: event
            indexBy: locale
            cascade: [persist, remove]
    manyToOne:
        scene:
            targetEntity: Domain\Entity\Scene
            joinColumn:
                onDelete: CASCADE
        createdBy:
            targetEntity:  Domain\Entity\User
            joinColumn:
                onDelete: CASCADE
