---
App\Entity\Translation\CharacterTranslation:
    type: entity
    table: character_entity_translation
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
        description:
            type: text
            nullable: true
        locale:
            type: string
            length: 2
            fsi:
                translatable:
                    locale: ~
    manyToOne:
        character:
            targetEntity: App\Entity\Character
            inversedBy: translations
            joinColumn:
                onDelete: "CASCADE"
