---
App\Entity\User:
    type: entity
    table: app_user
    repositoryClass: App\Repository\Doctrine\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            unique: true
        password: ~
        active:
            type: boolean
        roles:
            type: json_array
    oneToMany:
        activationTokens:
            targetEntity: App\Entity\User\ActivationToken
            mappedBy: user
            cascade: ["persist", "remove"]
            orderBy:
                createdAt: DESC
        passwordResetTokens:
            targetEntity: App\Entity\User\PasswordResetToken
            mappedBy: user
            cascade: ["persist", "remove"]
            orderBy:
                createdAt: DESC
