---
Domain\Book\Create\DTO:
    constraints:
        - AppBundle\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title' }
            repositoryMethod: entityExists
            path: title
            entityClass: AppBundle\Entity\Book
            message: book.exists
    properties:
        title:
            - NotBlank: ~

Domain\Book\Edit\DTO:
    constraints:
        - AppBundle\Validation\Constraints\UniqueDTO:
            fields: { title: 't.title' }
            id: id
            repositoryMethod: entityExists
            path: title
            entityClass: AppBundle\Entity\Book
            message: book.exists
    properties:
        title:
            - NotBlank: ~
