---
AppBundle\Event\Create\DTO:
    properties:
        name:
            - NotBlank: ~
        model:
            - NotBlank: ~
            - Valid: ~
        scene:
            - NotBlank: ~

AppBundle\Model\Meeting:
    constraints:
        - AppBundle\Validation\Constraints\Meeting: ~
    properties:
        root:
            - NotBlank: ~
        location:
            - NotBlank: ~
        relation:
            - NotBlank: ~
