---
AppBundle\Event\Create\DTO:
    constraints:
        - AppBundle\Validation\Constraints\UniqueDTO:
            fields: { name: 't.name', scene: 'e.scene' }
            repositoryMethod: entityExists
            path: name
            entityClass: AppBundle\Entity\Event
            message: event.exists
    properties:
        name:
            - NotBlank: ~
        model:
            - NotBlank: ~
            - Valid: ~
        scene:
            - NotBlank: ~

AppBundle\Model\Meeting:
    constraints:
        - AppBundle\Validation\Constraints\Meeting: ~
    properties:
        root:
            - NotBlank: ~
        location:
            - NotBlank: ~
        relation:
            - NotBlank: ~
