---
AppBundle\Location\Create\DTO:
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~

AppBundle\Location\Edit\DTO:
    properties:
        avatar:
            - FSi\Bundle\DoctrineExtensionsBundle\Validator\Constraints\Image: ~
        name:
            - NotBlank: ~
